### PR TITLE
ESP32-S2: Remove calloc in AnalogIn

### LINKED ISSUE #3809: AnalogIn crash
```
/home/tannewt/repos/circuitpython/ports/esp32s2/build-espressif_saola_1_wroom/esp-idf/../../esp-idf/components/esp_system/panic.c:360
/home/tannewt/repos/circuitpython/ports/esp32s2/build-espressif_saola_1_wroom/esp-idf/../../esp-idf/components/esp_system/system_api.c:104
/home/tannewt/repos/circuitpython/ports/esp32s2/build-espressif_saola_1_wroom/esp-idf/../../esp-idf/components/newlib/abort.c:46
/home/tannewt/repos/circuitpython/ports/esp32s2/build-espressif_saola_1_wroom/esp-idf/../../esp-idf/components/esp_adc_cal/esp_adc_cal_esp32s2.c:232 (discriminator 1)
/home/tannewt/repos/circuitpython/ports/esp32s2/common-hal/analogio/AnalogIn.c:73
/home/tannewt/repos/circuitpython/ports/esp32s2/../../shared-bindings/analogio/AnalogIn.c:116
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/objfun.c:72
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/runtime.c:624
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/runtime.c:1042
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/runtime.c:1085
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/runtime.c:1093
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/runtime.c:931
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/vm.c:333
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/objfun.c:286
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/runtime.c:624
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/vm.c:934
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/objfun.c:286
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/runtime.c:624
/home/tannewt/repos/circuitpython/ports/esp32s2/../../py/runtime.c:598
/home/tannewt/repos/circuitpython/ports/esp32s2/../../lib/utils/pyexec.c:114
/home/tannewt/repos/circuitpython/ports/esp32s2/../../lib/utils/pyexec.c:535
/home/tannewt/repos/circuitpython/ports/esp32s2/../../main.c:211
/home/tannewt/repos/circuitpython/ports/esp32s2/../../main.c:288
/home/tannewt/repos/circuitpython/ports/esp32s2/../../main.c:588
/home/tannewt/repos/circuitpython/ports/esp32s2/supervisor/port.c:281
/home/tannewt/repos/circuitpython/ports/esp32s2/build-espressif_saola_1_wroom/esp-idf/../../esp-idf/components/freertos/xtensa/port.c:535
```

### PR DESCRIPTION
**Pull request by hierophect**
My implementation of the ADC in AnalogIn brought in a calloc from the example code in the IDF that isn't necessary and may have been causing memory corruption. Removing it resolves #3809 on my Saola 1 (Wroom).

### CODE REVIEW

File: ports/esp32s2/common-hal/analogio/AnalogIn.c [hunk 1]
```diff
@@ -34,6 +34,8 @@
 
 #include "shared-bindings/microcontroller/Pin.h"
 
+#include <string.h>
+
 #define DEFAULT_VREF        1100
 #define NO_OF_SAMPLES       64
```
Comment (dhalbert) [inline ports/esp32s2/common-hal/analogio/AnalogIn.c:40]: I discussed this choice of averaging 64 samples with @ladyada, and we thought we could reduce this to 2 instead of 64. I did some instrumentation and all 64 values were fairly close; there's not a lot of need to average so many samples.

**Review by dhalbert — CHANGES_REQUESTED** [review]
The other changes look great. I just am suggesting reducing `NO_OF_SAMPLES` to speed things up.

File: ports/esp32s2/common-hal/analogio/AnalogIn.c (hunk 1 above)
Comment (hierophect) [reply ports/esp32s2/common-hal/analogio/AnalogIn.c:40]: Ok, I'll swap that out

**Review by jepler — APPROVED** [review]
[no testing performed, but checked that Dan's earlier requested change was incorporated]

**Comment by jepler** [comment]
Looks like this needs manual attention due to translation changes on the main branch.

**Review by dhalbert — CHANGES_REQUESTED** [review]
Looks good! Yes, just do a merge from upstream, try `make check-translate` and if that complains , a `make translate`.

**Review by dhalbert — APPROVED** [review]
:+1: Can merge if builds are fine.
