### PR TITLE
Rpi port i2ctarget fixes

### LINKED ISSUE #10423: I2CTarget transactions are spread across multiple requests on raspberrypi
### CircuitPython version and board name

```python
Adafruit CircuitPython 10.0.0-alpha.6-2-gc6e4d72cd3 on 2025-05-21; Pimoroni Pico Plus 2 W with rp2350b
(adafruit-circuitpython-pimoroni_pico_plus2w-en_US-20250521-main-PR10366-c6e4d72.uf2)
```

### Code/REPL

`raspberrypi` `i2ctarget` code (only reads):

```python
import board
from i2ctarget import I2CTarget

I2C_ADDRESS = 0x40

# Pico Plus 2 W
with I2CTarget(scl=board.GP5, sda=board.GP4, addresses=(I2C_ADDRESS,)) as device:
    while True:
        req = device.request(timeout=-1)  # Zero means wait forever, a negative value means check once
        if not req:
            continue
        with req as r:
            inbuf = r.read(-1)  # n – Number of bytes to read (negative means all)
            print(f"READ {len(inbuf)} {inbuf}")
```

I2C Controller code (only writes):

```py
import time
import board

I2C_ADDRESS = 0x40

# UnexpectedMaker FeatherS3
i2c = board.STEMMA_VERTICAL_I2C()

while True:
    outbuf = bytearray(b'abcd')
    print(f"WRITE {outbuf} ", end="")
    while not i2c.try_lock():
        pass
    try:
        i2c.writeto(I2C_ADDRESS, outbuf)
        print(f"written")
    except Exception:
        print(f"not written")
    i2c.unlock()

    time.sleep(2)
```

### Behavior

I2C Controller output:
```
WRITE bytearray(b'abcd') written
WRITE bytearray(b'abcd') written
WRITE bytearray(b'abcd') written
WRITE bytearray(b'abcd') written
```

i2ctarget output:
```
READ 2 bytearray(b'ab')
READ 2 bytearray(b'cd')
READ 1 bytearray(b'a')
READ 3 bytearray(b'bcd')
READ 1 bytearray(b'a')
READ 3 bytearray(b'bcd')
READ 1 bytearray(b'a')
READ 3 bytearray(b'bcd')
```

### Description

Using post-alpha.6 firmware that incorporates the `i2ctarget` request `deinit` [fix](https://github.com/adafruit/circuitpython/pull/10366) for `raspberrypi`. `i2ctarget` code works as expected  on `atmel-samd`, even with very large transaction payloads. `raspberrypi` handles 1 or 2 bytes OK, but anything larger gets split across multiple requests unpredictably. The end result is that it's impossible to delineate separate transactions.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by FoamyGuy**
This supercedes #10474. It contains the original commit from 10474 and a new commit that resolves the changes that were requested on that PR. 

This also resolves #10423. While looking into this and testing the refactored fix I found this issue and the reproducer code in it and took a quick shot at resolving it with help from claude.

The root cause of 10423 is read_byte was checking the RX FIFO status (RFNE) once and returning 0 immediately if empty. At I2C bus speeds (even 400kHz), the CPU runs much faster than bytes arrive on the wire. So after reading the first 1-2 bytes, the CPU would check the FIFO, find it momentarily empty (the next byte hasn't clocked in yet), return 0, and the shared-bindings read() loop would break — splitting a single 4-byte transfer into two 2-byte reads.

I tested with the reproducer code in the issue and with this fix the pico side is now able to successfully read messages larger than 1 or two bytes. The 4 from the original code work fine and I tested 16 bytes and found it working as well.

### CODE REVIEW

File: ports/raspberrypi/common-hal/i2ctarget/I2CTarget.c [hunk 1]
```diff
@@ -98,12 +105,20 @@ int common_hal_i2ctarget_i2c_target_is_addressed(i2ctarget_i2c_target_obj_t *sel
...
 int common_hal_i2ctarget_i2c_target_read_byte(i2ctarget_i2c_target_obj_t *self, uint8_t *data) {
-    if (self->peripheral->hw->status & I2C_IC_STATUS_RFNE_BITS) {
-        *data = (uint8_t)self->peripheral->hw->data_cmd;
-        return 1;
-    } else {
-        return 0;
+    // Wait for data to arrive or a STOP condition indicating the transfer is over.
+    // Without this wait, the CPU can drain the FIFO faster than bytes arrive on the
+    // I2C bus, causing transfers to be split into multiple partial reads.
+    for (int t = 0; t < 100; t++) {
```
Comment (tannewt) [inline ports/raspberrypi/common-hal/i2ctarget/I2CTarget.c:111]: Do we want to formalize the timeout here? Maybe based on the baudrate?

**Review by tannewt — COMMENTED** [review]
Thanks for picking this up! One question before we merge.

File: ports/raspberrypi/common-hal/i2ctarget/I2CTarget.c (hunk 1 above)
Comment (FoamyGuy) [reply ports/raspberrypi/common-hal/i2ctarget/I2CTarget.c:111]: This is my first experience with i2ctarget side, so I'm not sure of the details. But talking it over with claude a bit and seems like the target side code does not have a reliable way to know the baudrate. The raspberrypi port implementation makes reference to setting a value here: https://github.com/FoamyGuy/circuitpython/blob/e376e2416b84d7b06f3f74843682d1d74d13efd4/ports/raspberrypi/common-hal/i2ctarget/I2CTarget.c#L52-L53 but the comment indicates it's not used. 

Claude had this to say about the idea of basing it on bus speed: 
> the current fix is already effectively speed-independent — the loop exits early via the R_STOP_DET check as soon as the master finishes the transfer. The 1ms ceiling (100 × 10µs) is just a safety timeout, not a tuned wait. At the slowest standard I2C speed (100kHz), one byte is 9 clocks = 90µs, so 4 bytes would be ~360µs, well within the 1ms budget. The loop won't actually spin for 1ms in normal operation; it'll break out as soon as either data arrives or STOP is detected.

The values that it chose came from the atmel-samd implementation I think: https://github.com/FoamyGuy/circuitpython/blob/e376e2416b84d7b06f3f74843682d1d74d13efd4/ports/atmel-samd/common-hal/i2ctarget/I2CTarget.c#L148-L150

**Review by anecdata — COMMENTED** [review]
Confirmed testing results for #10423 

Config: M4 I2C Controller writing large packets to an M4 I2C Target and a RP2350 I2C Target. RP2350 I2C Target now reads successfully. Thanks FoamyGuy !

**Review by tannewt — APPROVED** [review]
Ok, thanks for the fix!
