### PR TITLE
Fix handling of zero-length pulseout pulse

### LINKED ISSUE #6735: pulseio.PulseOut's send function hanging project
### CircuitPython version

```python
Adafruit CircuitPython 7.3.2 on 2022-07-20; Adafruit Circuit Playground Bluefruit with nRF52840
```

### Code/REPL

```python
# NOTE: This is modified from the adafruit-irremote example irremote_transmit.py. Removed the use of the irremote library to make the issue clearer.
import pulseio
import pwmio
import board
import digitalio
import array

# Create a button object to trigger IR transmit
button = digitalio.DigitalInOut(board.D4)
button.direction = digitalio.Direction.INPUT
button.pull = digitalio.Pull.DOWN

# Create a 'pwmio' output, to send infrared signals on the IR transmitter @ 38KHz
pwm = pwmio.PWMOut(board.D9, frequency=38000, duty_cycle=2**15)
pulseout = pulseio.PulseOut(pwm)

data = array.array('H', (9500, 4500, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 1700, 550, 1700, 550, 1700, 550, 1700, 550, 1700, 550, 1700, 550, 550, 550, 1700, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 550, 1700, 550, 1700, 550, 1700, 550, 1700, 550, 1700, 550, 1700, 550, 1700, 550, 1700, 0))


while True:
    if button.value:
        print("IR signal sent!")
        pulseout.send(data)
        print("Done sending!")
```

### Behavior

When the button is pressed, IR signal sent! is printed to serial.
Done sending! never prints to serial. The program does not loop. It hangs at the send function.
Soft-resetting (e.g. saving the code.py file to the Circuit Playground) does not restart the program or remove the hung state.
The only way to get out of the hung state is to hard reset (reset button or power cycle).

### Description

Encountered this while trying to transmit an IR signal along with other functions in the same script. I found that once it reaches the IR transmission the code does not execute further. Troubleshooting within the adafruit-irremote library file allowed me to isolate the line on which this is occurring and simplify the recreation of the bug to the small bit of code above.

It is a huge hinderance as it means any Circuit Playground transmitting an IR signal can do nothing else, including remove itself from that transmission state. The larger issue must be within pulseio itself but I wasn't able to poke my head in the codebase easily to see (nor do I think my coding is up to the repo's standards), so assistance in resolving this issue would be appreciated.

Thanks all!

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by DavePutz**
Attempting a zero-length pulse in pulseout would mean on an NRF board that the interrupt timer would never fire; thus hanging the program. This patch will bypass and ignore any pulses with a length of 0.

Closes #6735.

### CODE REVIEW

**Comment by jepler** [comment]
[I updated the initial comment to have the special syntax for auto-closing the related issue]

File: ports/nrf/common-hal/pulseio/PulseOut.c [hunk 1]
```diff
@@ -74,6 +74,11 @@ static void pulseout_event_handler(nrf_timer_event_t event_type, void *p_context
     nrfx_timer_pause(timer);
 
     pulse_array_index++;
+    // Ignore a zero-length pulse
+    while (pulse_array[pulse_array_index] == 0 &&
+           pulse_array_index < pulse_array_length) {
+        pulse_array_index++;
+    }
```
Comment (jepler) [inline ports/nrf/common-hal/pulseio/PulseOut.c:81]: shouldn't the two halves of this test be in the other order, so that the length is checked first?  otherwise, there's the possibility of reading one item past the end of the pulse array.

**Review by jepler — CHANGES_REQUESTED** [review]

File: ports/nrf/common-hal/pulseio/PulseOut.c (hunk 1 above)
Comment (DavePutz) [reply ports/nrf/common-hal/pulseio/PulseOut.c]: Yes, I see your point. I generally write the less likely expression first to speed things up, but that doesn't work here. Change has been made as suggested.

**Review by dhalbert — APPROVED** [review]
This looks good to me now -- thanks! Will merge and backport to 7.3.x.
