### PR TITLE
STM32: I2C fix & general busio cleanup

### LINKED ISSUE #2172: STM32: Improve I2C reset workaround
I2C currently has problems resetting after a soft reboot, such as after a write to disk. The error is actually not listed in the F4 errata, but follows the exact pattern of the "I2C analog filter may provide wrong value" error listed in the F10xx erratas [here](https://www.st.com/content/ccc/resource/technical/document/errata_sheet/f5/50/c9/46/56/db/4a/f6/CD00197763.pdf/files/CD00197763.pdf/jcr:content/translations/en.CD00197763.pdf) (2.14.7) and [here](https://www.st.com/content/ccc/resource/technical/document/errata_sheet/7d/02/75/64/17/fc/4d/fd/CD00190234.pdf/files/CD00190234.pdf/jcr:content/translations/en.CD00190234.pdf#page26)(2.13.7). Stack exchange discussion is [here](https://electronics.stackexchange.com/questions/272427/stm32-busy-flag-is-set-after-i2c-initialization).

The current workaround for this error is crude and not fully implemented as advised in the errata, and could be improved to match the recommended solution.

### PR DESCRIPTION
**Pull request by hierophect**
This PR revisits some of the differences that appeared between the busio modules as they were implemented and brings them closer together in terms of style and readability. Also reorganizes the fix for an issue with I2C that would occur on soft reboot - the code is now closer to comparable APIs like Arduino and MBED. Resolves #2172. Changed modules tested on STM32F405 feather and STM32F412 discovery.

### CODE REVIEW

File: ports/stm32f4/common-hal/busio/I2C.c [hunk 1]
```diff
@@ -35,51 +35,46 @@
...
+    i2c_clock_disable(ALL_CLOCKS & ~(never_reset_mask));
 }
 
-
 void common_hal_busio_i2c_construct(busio_i2c_obj_t *self,
         const mcu_pin_obj_t* scl, const mcu_pin_obj_t* sda, uint32_t frequency, uint32_t timeout) {
 
     //match pins to I2C objects
     I2C_TypeDef * I2Cx;
+    uint8_t sda_len = sizeof(mcu_i2c_sda_list) / sizeof(*mcu_i2c_sda_list);
```
Comment (jepler) [inline ports/stm32f4/common-hal/busio/I2C.c]: While it's not used consistently, it's worth noting that there's a macro for this...
py/misc.h:#define MP_ARRAY_SIZE(a) (sizeof(a) / sizeof((a)[0]))

File: ports/stm32f4/common-hal/busio/I2C.c [hunk 2]
```diff
@@ -238,11 +195,56 @@ void common_hal_busio_i2c_unlock(busio_i2c_obj_t *self) {
...
         uint8_t *data, size_t len) {
-    return HAL_I2C_Master_Receive(&(self->handle), (uint16_t)(addr<<1), data, (uint16_t)len, 500) == HAL_OK ? 0 : MP_EIO;
+    return HAL_I2C_Master_Receive(&(self->handle), (uint16_t)(addr<<1), data, (uint16_t)len, 500) 
+                                    == HAL_OK ? 0 : MP_EIO;
+}
+
+STATIC void i2c_clock_enable(uint8_t mask) {
+    //Note: hard reset required due to soft reboot issue. 
+    #ifdef I2C1
+    if (mask & 1<<0) {
```
Comment (jepler) [inline ports/stm32f4/common-hal/busio/I2C.c]: My personal style would parenthesize (1<<0) and so on, but I don't know whether that's CP style or not.

Comment (dhalbert) [reply ports/stm32f4/common-hal/busio/I2C.c]: I think if the precedence is pretty clear we don't parenthesize, but we do sometimes just for readability. No hard and fast rules on that.

File: ports/stm32f4/common-hal/busio/SPI.c [hunk 3]
```diff
@@ -60,13 +59,39 @@ STATIC uint32_t get_busclock(SPI_TypeDef * instance) {
...
+    } while (divisor != 256);
+    //only gets here if requested baud is lower than minimum
+    *prescaler = 256;
+    return SPI_BAUDRATEPRESCALER_256;
+}
+
 void spi_reset(void) {
     uint16_t never_reset_mask = 0x00;
-    for(int i=0;i<MAX_SPI;i++) {
+    for (int i = 0; i < MAX_SPI; i++) {
```
Comment (dhalbert) [inline ports/stm32f4/common-hal/busio/SPI.c]: Not a big deal but I usually use `size_t` for unsigned indices.

File: ports/stm32f4/common-hal/busio/UART.c [hunk 4]
```diff
@@ -567,33 +568,53 @@ STATIC void uart_clock_disable(uint16_t mask) {
 
 STATIC void uart_assign_irq(busio_uart_obj_t *self, USART_TypeDef * USARTx) {
     #ifdef USART1
```
Comment (dhalbert) [inline ports/stm32f4/common-hal/busio/UART.c]: Maybe make this a table lookup or a `switch`, still with appropriate `#ifdef`'s.

File: ports/stm32f4/common-hal/busio/I2C.c (hunk 2 above)
Comment (hierophect) [reply ports/stm32f4/common-hal/busio/I2C.c]: I think it'd look a little better here so I'll put it in.

File: ports/stm32f4/common-hal/busio/I2C.c (hunk 1 above)
Comment (hierophect) [reply ports/stm32f4/common-hal/busio/I2C.c]: noice I'll use it.

File: ports/stm32f4/common-hal/busio/I2C.c [hunk 5]
```diff
@@ -163,13 +123,26 @@ void common_hal_busio_i2c_construct(busio_i2c_obj_t *self,
...
     claim_pin(scl);
 }
 
+void common_hal_busio_i2c_never_reset(busio_i2c_obj_t *self) {
+    for (size_t i = 0; i < MP_ARRAY_SIZE(mcu_i2c_banks); i++) {
+        if (self->handle.Instance == mcu_i2c_banks[i]) {
+            never_reset_i2c[i] = true;
+
+            never_reset_pin_number(self->scl->pin->port, self->scl->pin->number);
+            never_reset_pin_number(self->sda->pin->port, self->scl->pin->number);
```
[the remark this answers is not in the document]
Comment (hierophect) [reply ports/stm32f4/common-hal/busio/I2C.c]: whoop thanks for finding that.

File: ports/stm32f4/common-hal/busio/UART.c (hunk 4 above)
Comment (hierophect) [reply ports/stm32f4/common-hal/busio/UART.c]: I guess the switch would be like:
```
switch (USARTx)
{
#ifdef USART1
    case USART1: self->irq = USART1_IRQn;
        break;
#endif
#ifdef USART2
//etc
    default: // code to be executed if n doesn't match any cases
}
```
But how would a table lookup work without extractable index information? And would the reason for one of these be just code line reduction, or is it something else?

Comment (dhalbert) [reply ports/stm32f4/common-hal/busio/UART.c]: The table would be like:
```
{ USART1, USART1_IRQn },
{ USART2, USART2_IRQn },
```
etc.
I think a `switch` is fine. The main thing is that the current structure has each if statement fall into the next one. If the compiler is clever it won't be extra code. You could add `else if` instead. But I think a `switch` is cleaner.

File: ports/stm32f4/common-hal/busio/SPI.c (hunk 3 above)
Comment (hierophect) [reply ports/stm32f4/common-hal/busio/SPI.c]: Seems like Scott uses just raw int as I do. Let's revisit this if we want to make it consistent across ports.

File: ports/stm32f4/common-hal/busio/UART.c (hunk 4 above)
Comment (hierophect) [reply ports/stm32f4/common-hal/busio/UART.c]: Whoops, can't switch on pointer values.

Comment (hierophect) [reply ports/stm32f4/common-hal/busio/UART.c]: The table's going to be kind of ugly too, since I'll either need to assign an empty row for every undefined category or have the size be dynamic. Are you set on me changing this?

Comment (dhalbert) [reply ports/stm32f4/common-hal/busio/UART.c]: ok, never mind, not a big deal
