### PR TITLE
rp2040: uart: check all pins before claiming any

### LINKED ISSUE #9424: RP2040 busio.UART not freeing pin after detecting invalid pins
```py
Adafruit CircuitPython 9.1.0-rc.0 on 2024-07-09; Adafruit Metro RP2040 with rp2040
>>> import board, busio
>>> u = busio.UART(board.SDA, board.SCL)
>>> u.deinit()
>>> u = busio.UART(board.SDA, board.SCL)
>>> u.deinit()
>>> u = busio.UART(board.SDA, board.A0)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Invalid pins
>>> u = busio.UART(board.SDA, board.A1)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: SDA in use
```
SDA should not be in use.

User in discord encountered this when trying to run the [Where's My UART](https://learn.adafruit.com/circuitpython-essentials/circuitpython-uart-serial#wheres-my-uart-2985036) code.

### PR DESCRIPTION
**Pull request by jepler**
also remove the comment that pin_init may raise an exception for an in-use pin; this is incorrect. The unclaimed status of all pins was verified in shared-bindings before calling construct.

closes #9424

### CODE REVIEW

File: ports/raspberrypi/common-hal/busio/UART.c [hunk 1]
```diff
@@ -42,13 +42,16 @@ void never_reset_uart(uint8_t num) {
     uart_status[num] = STATUS_NEVER_RESET;
 }
 
+static void pin_check(const uint8_t uart, const mcu_pin_obj_t *pin, const uint8_t pin_type) {
+    if (!(((pin->number % 4) == pin_type) && ((((pin->number + 4) / 8) % NUM_UARTS) == uart))) {
```
Comment (dhalbert) [inline ports/raspberrypi/common-hal/busio/UART.c:46]: I tested on a Metro RP2040 and discovered that now no combination of pins was valid. This is because if any pins are `NULL` (e.g. `cts` or `rts`, in the typical case), this will raise "invalid pin". I think this will fix it.

```suggestion
    if (pin == NULL) {
        return;
    }
    if (!(((pin->number % 4) == pin_type) && ((((pin->number + 4) / 8) % NUM_UARTS) == uart))) {
```

**Review by dhalbert — CHANGES_REQUESTED** [review]

**Comment by jepler** [comment]
thanks for the fix and thanks for being gracious about a PR I obviously didn't do more than compile-test.

**Review by dhalbert — APPROVED** [review]
Tested works, thanks!
