### PR TITLE
fix atmel-samd DAC channel selection logic

### LINKED ISSUE #3962: analogio refuse to change the value
Testing on
> Adafruit CircuitPython 6.1.0-rc.0 on 2021-01-06; Adafruit Feather M0 Express with samd21g18

analogio seems to fail when I try to change the value:
```
import board
from analogio import AnalogOut
analog_out = AnalogOut(board.A0)
analog_out.value = 1000
analog_out.value = 2000

```

The result is and error on the line that set the value to 2000:

> main.py output:
> Traceback (most recent call last):
>   File "main.py", line 5, in <module>
> ValueError: Object has been deinitialized and can no longer be used. Create a new object.

When trying the guide code from https://learn.adafruit.com/circuitpython-essentials/circuitpython-analog-out it fail on the line: `analog_out.value = i`

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #3962 (@dglaude).

- Pin channel `if` statements tested opposite condition.
- `PA05` check not guarded by SAMx5 check.

Rewrote as a `switch` statement.

Tested on SAMD21 and SAMD51.

### CODE REVIEW

File: ports/atmel-samd/common-hal/analogio/AnalogOut.c [hunk 1]
```diff
@@ -55,21 +55,22 @@ void common_hal_analogio_analogout_construct(analogio_analogout_obj_t* self,
...
-        mp_raise_ValueError(translate("AnalogOut not supported on given pin"));
+    uint8_t channel;
+    switch (pin->number) {
+        #if defined(PIN_PA02) && !defined(IGNORE_PIN_PA02)
+        case PIN_PA02:
+            channel = 0;
+            break;
+        #endif
+
+       #if defined(SAM_D5X_E5X) && defined(PIN_PA05) && defined(PIN_PA05) && !defined(IGNORE_PIN_PA05)
```
Comment (tannewt) [inline ports/atmel-samd/common-hal/analogio/AnalogOut.c:66]:
```suggestion
       #if defined(SAM_D5X_E5X) && defined(PIN_PA05) && !defined(IGNORE_PIN_PA05)
```

**Review by tannewt — CHANGES_REQUESTED** [review]
One nit that the original code had. Switch is easier to read. Thanks!

**Review by tannewt — APPROVED** [review]

**Comment by dhalbert** [comment]
Some bad builds: some just network trouble, others are too big. Will fix later. Merging now.
