### PR TITLE
Don't update status LED color on brightness change

### LINKED ISSUE #5872: supervisor.set_rgb_status_brightness crashes on FunHouse
From the REPL, on a Fun House.
```py
import supervisor
supervisor.set_rgb_status_brightness(0)
```
Causes a reboot of the board.
On latest it reboots into Hard Crash safe mode, on 7.1.1 it just resets.

I tested it on QTPY ESP32, Clue, Gemma (because of the dotstar), FeatherS2 (ESP and dotstar) and could not reproduce.

### PR DESCRIPTION
**Pull request by tannewt**
Brightness changes now happen when the LED isn't active or
initialized. When not init, CP may crash.

Fixes #5872

### CODE REVIEW

File: shared-bindings/supervisor/__init__.c [hunk 1]
```diff
@@ -76,16 +76,15 @@ STATIC mp_obj_t supervisor_disable_autoreload(void) {
...
 //|     ...
 //|
 STATIC mp_obj_t supervisor_set_rgb_status_brightness(mp_obj_t lvl) {
     // This must be int. If cast to uint8_t first, will never raise a ValueError.
     int brightness_int = mp_obj_get_int(lvl);
-    if (brightness_int < 0 || brightness_int > 255) {
-        mp_raise_ValueError(translate("Brightness must be between 0 and 255"));
-    }
+    mp_arg_validate_int_range(brightness_int, 0, 255, MP_QSTR_brightness);
     set_status_brightness((uint8_t)brightness_int);
```
Comment (dhalbert) [inline shared-bindings/supervisor/__init__.c:88]: [GitHub won't let me do a suggestion]
`mp_arg_validate_int_range()` returns the int, so you can do this all in one go:
```c
    set_status_brightness((uint8_t)mp_arg_validate_int_range(mp_obj_get_int(lvl), 0, 255, MP_QSTR_brightness));
```

**Review by dhalbert — CHANGES_REQUESTED** [review]
Great! Just one suggestion.

File: shared-bindings/supervisor/__init__.c (hunk 1 above)
Comment (tannewt) [reply shared-bindings/supervisor/__init__.c:88]: I'd rather not. I think the multi-line version is easier to read. They should compile to the same thing.

**Review by dhalbert — APPROVED** [review]

**Comment by tannewt** [comment]
CI failure is an unrelated network issue.
