### PR TITLE
Xiao led pins

### LINKED ISSUE #6120: seeeduino_xiao SAMD21 port has incorrect/insufficient LED pin definitions
### CircuitPython version

```python
Adafruit CircuitPython 7.2.0 on 2022-02-24; Seeeduino XIAO with samd21g18
```

### Code/REPL

```python
import board
import digitalio
l1 = digitalio.DigitalInOut(board.LED)
l1.direction = digitalio.Direction.OUTPUT
# in Xiao 1/True is off, 0/False is on for LEDs
l1.value = True     
l1.value = False
l1.value = True
# first error ... same port for BLUE_LED
#                            and D13
l2 = digitalio.DigitalInOut(board.BLUE_LED)
###
l1.deinit()
l2 = digitalio.DigitalInOut(board.BLUE_LED)
 
l2 = digitalio.DigitalInOut(board.BLUE_LED)
i1.direction = digitalio.Direction.OUTPUT
i2.direction = digitalio.Direction.OUTPUT
i1.value = False
i2.value = False
l2.direction = digitalio.Direction.OUTPUT
l2.value = True      # amber LED off    
l2.value = False     # amber LED on
l2.value = True      # amber LED off
```

### Behavior

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: D13 in use
### Description

in circuitpython/ports/atmel-samd/boards/seeeduion_xiao/pins.c LED pins are defined:
```
    // LED pins
    { MP_ROM_QSTR(MP_QSTR_LED),   MP_ROM_PTR(&pin_PA17) }, // status
    { MP_ROM_QSTR(MP_QSTR_BLUE_LED),   MP_ROM_PTR(&pin_PA17) },
```
LED is correct wired to PA17- to an amber/yellow/orange(?) LED.  Same as D13
BLUE_LED points to the same port- PA17 

The Xiao has two different blue LEDs, wired to the UART RX and TX pins and available for a user.  These are wired to PA18 (RX) and PA19 (TX) on the chip.  A suggested modification is:
```
    // LED pins
    { MP_ROM_QSTR(MP_QSTR_LED),   MP_ROM_PTR(&pin_PA17) }, // status
    { MP_ROM_QSTR(MP_QSTR_RX_LED),   MP_ROM_PTR(&pin_PA18) },
    { MP_ROM_QSTR(MP_QSTR_TX_LED),   MP_ROM_PTR(&pin_PA19) },
```

### Additional information

I rebuilt the xiao firmware with the modifications and the LEDs work as desired I think.  Still a double definition between D13 and LED at PA17

### PR DESCRIPTION
**Pull request by ricksorensen**
Fixes #6120.

Modify and correct LED pin mappings and names for Seeduino SAMD21 Xiao
    Added YELLOW_LED=LED=D13,
          BLUE1_LED=RX_LED,
          BLUE2_LED=TX_LED
     Added clarifying comments about duplicate names for pins, and reverse wiring for LEDs on XIAO

### CODE REVIEW

File: ports/atmel-samd/boards/seeeduino_xiao/pins.c [hunk 1]
```diff
@@ -29,7 +29,7 @@ STATIC const mp_rom_map_elem_t board_module_globals_table[] = {
     { MP_ROM_QSTR(MP_QSTR_D8), MP_ROM_PTR(&pin_PA07) },
     { MP_ROM_QSTR(MP_QSTR_D9), MP_ROM_PTR(&pin_PA05) },
     { MP_ROM_QSTR(MP_QSTR_D10), MP_ROM_PTR(&pin_PA06) },
-    { MP_ROM_QSTR(MP_QSTR_D13), MP_ROM_PTR(&pin_PA17) },
+    { MP_ROM_QSTR(MP_QSTR_D13), MP_ROM_PTR(&pin_PA17) },  // yellow_led
```
Comment (dhalbert) [inline ports/atmel-samd/boards/seeeduino_xiao/pins.c:32]: Remove this, because we no longer use D13 for most boards except those that traditionally have D13, such as Arduino-shaped-boards.
```suggestion
```

File: ports/atmel-samd/boards/seeeduino_xiao/pins.c [hunk 2]
```diff
@@ -44,9 +44,17 @@ STATIC const mp_rom_map_elem_t board_module_globals_table[] = {
...
+    //                                     low/0/False turns LED ON
+    //    duplicate names for test LED ... see D13
+    { MP_ROM_QSTR(MP_QSTR_LED),   MP_ROM_PTR(&pin_PA17) },
+    { MP_ROM_QSTR(MP_QSTR_YELLOW_LED),   MP_ROM_PTR(&pin_PA17) },
+    //    2 blue LEDs ... uart rx/tx indicator is default use
+    { MP_ROM_QSTR(MP_QSTR_RX_LED),   MP_ROM_PTR(&pin_PA18) },
+    { MP_ROM_QSTR(MP_QSTR_TX_LED),   MP_ROM_PTR(&pin_PA19) },
+    //    create duplicate mappings with BLUE in name
+    { MP_ROM_QSTR(MP_QSTR_BLUE1_LED),   MP_ROM_PTR(&pin_PA18) },
+    { MP_ROM_QSTR(MP_QSTR_BLUE2_LED),   MP_ROM_PTR(&pin_PA19) },
```
Comment (dhalbert) [inline ports/atmel-samd/boards/seeeduino_xiao/pins.c:57]: 1. Group aliases for the same pin together, with blank lines in between group.
2. All these LED pins are active-low, so we add the `_INVERTED` suffix on such pins. (So there is no plain `board.LED` any more.)
3. You can omit the comments because the names are pretty self-explanatory.
4. We have tended to add a number after the word `LED`

To see all the LED names in use (not completely consistent):
```sh
grep _LED ports/*/boards/*/pins.c
```

```suggestion
    { MP_ROM_QSTR(MP_QSTR_LED_INVERTED),   MP_ROM_PTR(&pin_PA17) },
    { MP_ROM_QSTR(MP_QSTR_YELLOW_LED_INVERTED),   MP_ROM_PTR(&pin_PA17) },
    
    { MP_ROM_QSTR(MP_QSTR_RX_LED_INVERTED),   MP_ROM_PTR(&pin_PA18) },
    { MP_ROM_QSTR(MP_QSTR_BLUE_LED1_INVERTED),   MP_ROM_PTR(&pin_PA18) },

    { MP_ROM_QSTR(MP_QSTR_TX_LED_INVERTED),   MP_ROM_PTR(&pin_PA19) },
    { MP_ROM_QSTR(MP_QSTR_BLUE_LED2_INVERTED),   MP_ROM_PTR(&pin_PA19) },
```

**Review by dhalbert — CHANGES_REQUESTED** [review]
Thanks! I've changed the names and ordering a bit, for the reasons given. If you are OK with these (and I didn't make a mistake!), you can accept these changes by pressing the "Commit suggestion" or "Add suggestion to batch" (and then committing the whole batch).

**Review by ricksorensen — COMMENTED** [review]
Look okay to me

**Review by dhalbert — APPROVED** [review]
