### PR TITLE
Fix crash on raise of reload exception

### LINKED ISSUE #5132: Crash on auto reload on ESP32S2
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-alpha.6 on 2021-08-12; FeatherS2 with ESP32S2
```
All the way down to:
```python
Adafruit CircuitPython 7.0.0-alpha.5-117-gbe2342f32 on 2021-08-06; FeatherS2 with ESP32S2
```

### Code/REPL

```python
# code.py
while True:
  pass
```

### Behavior

On file saving, when the code is running, the board disconnects from USB and resets (and comes back).

### Description

- Happens if the code is running, even during a single time.sleep() (no while loop).
- Doesn't seem to happen if the code has finished.
- Reproduced on mac and windows.
- Reproduced with two different Feather S2 and a FunHouse.
- Reproduced with or without TinyUF2.
- Manual reload from the REPL (ctrl-C ctrl-D) doesn't cause a reset.
- Adding `supervisor.disable_autoreload()` to code.py stops the issue (saving a file doesn't cause a reset).

It now resets to safe mode, but it used to reset to normal mode with tinyuf2 (on the feather). It might be because I updated it with update.uf2, but now after different tests I erased the flash and reinstalled tinyuf2 from bin. I don't *know* if that is related to that issue, but it's worth noting that one might or might not see safe mode after reset.

`be2342f32` is the earliest version I could reproduce the issue with, so it seems related to  #5072 

### Additional information

Reported on discord by Docteh with a generic wrover module.

### PR DESCRIPTION
**Pull request by microDev1**
Closes #5132.

### CODE REVIEW

**Review by dhalbert — APPROVED** [review]
Aha, thanks! Did not test, but I'm sure you did.

File: py/runtime.c [hunk 1]
```diff
@@ -86,7 +86,8 @@ void mp_init(void) {
 
     MP_STATE_VM(mp_reload_exception).base.type = &mp_type_ReloadException;
     MP_STATE_VM(mp_reload_exception).args = (mp_obj_tuple_t *)&mp_const_empty_tuple_obj;
-    MP_STATE_VM(mp_reload_exception).traceback = (mp_obj_traceback_t *)&mp_const_empty_traceback_obj;
+    MP_STATE_VM(mp_reload_exception).traceback = &MP_STATE_VM(mp_reload_traceback);
+    *MP_STATE_VM(mp_reload_exception).traceback = mp_const_empty_traceback_obj;
```
Comment (tannewt) [inline py/runtime.c:90]: Is this right?
```
// Initialize the reload traceback as empty to begin with. It will be filled in later when the exception is raised.
MP_STATE_VM(mp_reload_traceback) = mp_const_empty_traceback_obj;
```

Comment (microDev1) [reply py/runtime.c:90]: > Initialize the reload traceback as empty to begin with. It will be filled in later when the exception is raised.

Not sure what you are asking here exactly but the above statement is correct.

Comment (tannewt) [reply py/runtime.c:90]: I want to suggest the code I put as a clearer version of what you are doing. I was hoping you'd let me know if the comment was correct. This PR doesn't have much explanation of what the original issue was and how you are fixing it.

Comment (microDev1) [reply py/runtime.c:90]: Pointing `traceback` to `const` leads to a crash as `mp_obj_exception_add_traceback` expects a modifiable value.
The crash happens at the following line when trying to re-assign a const struct field:
https://github.com/adafruit/circuitpython/blob/0569c202efbc393dcfc4b95d2472024a6c309b08/py/objexcept.c#L573
Pointing `traceback` to `MP_STATE_VM(mp_reload_traceback)` instead allows a future modification.
Hope this clears things up. :)

Comment (dhalbert) [reply py/runtime.c:90]: Since this required a conversation, could you add some comments to the code explicating a bit? Thanks.

Comment (microDev1) [reply py/runtime.c:90]: Sure, I am working on a test for `traceback` module and I'll add this with it.

Comment (tannewt) [reply py/runtime.c:90]: Thank you!
