### PR TITLE
Turn on unicode for FATFS

### LINKED ISSUE #5146: FileTransferProtocol: problems with non-ascii filenames
**CircuitPython version**

Adafruit CircuitPython 7.0.0-alpha.5 on Circuit Playground Bluefruit

**Behavior**
These problems are related to the Bluetooth FileTransferProtocol

Filenames with accents can be created but cannot be removed. 
For example if you create a folder named "Carpeta sin título" ("untitled folder" in Spanish) it is not possible to remove it later

Filenames with emojis cause bigger problems. 
Creating a folder using the  with an emoji name will make the listDirectory command return incorrect data that does not follow the protocol.
If an existing folder created via USB contains emojis the listDirectory command returns correct data, but the name reported is wrong.

### PR DESCRIPTION
**Pull request by tannewt**
This also tweaks the repr for unicode strings to only escape a few
utf-8 code points. This makes emoji show in os.listdir() for
example.

Also, enable exfat support on full builds.

Fixes #5146

### CODE REVIEW

File: lib/oofatfs/ff.c [hunk 1]
```diff
@@ -1175,6 +1175,7 @@ static DWORD get_fat (      /* 0xFFFFFFFF:Disk error, 1:Internal error, 2..0x7FF
                     break;
                 }
             }
+            MP_FALLTHROUGH
```
Comment (jepler) [inline lib/oofatfs/ff.c:1178]: Good to see these being added

**Review by jepler — DISMISSED** [review]
Thanks! Looks good, much simpler than I worried it would be!

**Review by dhalbert — APPROVED** [review]
LGTM, and we can do more about the error messages issue in another PR
