### PR TITLE
Fix always zero AnalogIn on nordic

### LINKED ISSUE #9109: 9.0.x: nRF: AnalogIn.value always returns 0
Starting with early 9.0.0 releases, `AnalogIn` on nordic boards returns zero all the time, no matter what input is applied to the pin. For instance, even with `A0` tied to 3.3V, you see:

```py
>>> import analogio,board
>>> a0 = analogio.AnalogIn(board.A0)
>>> a0.value
0

```
The underlying code has not changed in some time.

We are currently using gcc13. I recompiled a `nordic` build 9.0.x with gcc10, and the problem goes away (!).

Thanks @caternuson for finding this.

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #9109.

This is quite mysterious. The underlying code hasn't changed in quite a while. nordic `AnalogIn.value` was always returning zero on 9.x.x builds, including some early betas. The problem starts appearing when gcc13 starts being used. Compiling with gcc10 or gcc12 causes the problem to go away.

While debugging, I added a printf which also caused the problem to go away. Adding  tiny delay calls almost anywhere also helped. Eventually I realized it may have been due to these calls acting as an optimization memory fence. Adding `asm volatile("": : : "memory");` had the same effect. I'm not sure whether this is a compiler bug or something else, but the fix works.

Also removed the logic to start with `value = -1`, which didn't seem necessary.

### CODE REVIEW

File: ports/nrf/common-hal/analogio/AnalogIn.c [hunk 1]
```diff
@@ -76,7 +76,13 @@ uint16_t common_hal_analogio_analogin_get_value(analogio_analogin_obj_t *self) {
...
     // so we completely re-initialize it.
 
-    nrf_saadc_value_t value = -1;
+    // Adding the "asm volatile" memory fence here or many places after this declaration
+    // fixes an issue with gcc13 which causes `value` to always be zero.
+    // Compiling with gcc10 or gcc12 is fine.
+    // It can also be fixed by declaring `value` to be static.
+    // I think I'd like to declare this as volatile, but that causes type errors.
+    nrf_saadc_value_t value = 0;
+    asm volatile ("" : : : "memory");
```
Comment (tannewt) [inline ports/nrf/common-hal/analogio/AnalogIn.c:85]: Should this go after the DMA (I assume) runs? Before we read it.

**Review by tannewt — CHANGES_REQUESTED** [review]
One question

File: ports/nrf/common-hal/analogio/AnalogIn.c (hunk 1 above)
Comment (dhalbert) [reply ports/nrf/common-hal/analogio/AnalogIn.c]: That makes more sense, but having the `asm volatile` _anywhere_ after the declaration worked. So I moved it. But that may be an idiosyncrasy of the optimized code. By rights it should be declared volatile, but the `nrf` routines don't expect that declaration.

Comment (dhalbert) [reply ports/nrf/common-hal/analogio/AnalogIn.c]: Moved and re-tested to confirm.

**Review by tannewt — APPROVED** [review]
Thank you!
