### PR TITLE
STM32: SPI clock rate fix and cleanup

### LINKED ISSUE #2304: stm32f4: SPI clock rates
@hierophect Could you check the baudrate calculation in `busio.SPI`? I was using an SPI clock to try to test the difference between the "bad" and "good" STM32 Feathers I have, and I got odd SPI clock rates on both:

| specified  | as measured on Saelae |
| ------------- | ------------- |
| 160 MHz | 20.83 MHz |
| 40 MHz | 10.42 MHz |
| 16 MHz |  5.208 MHz |
| 15 MHz | 5.208 MHz |
| 8 MHz  | 2.632 MHz  |
| 1 MHz | 328 kHz  |
| 100 kHz | 164 kHz|

### PR DESCRIPTION
**Pull request by hierophect**
This PR corrects an issue in the STM32 port where an incorrect bus clock was used to calculate frequency on several instances of the SPI peripheral, halving the clock rate. The module now correctly selects a bus clock based on SPI instance. Thanks @dhalbert for finding this!

Since SPI was one of the first modules created for the port, I've also taken the opportunity to clean it up a bit to bring it more in line with the other modules. 

resolves #2304

### CODE REVIEW

File: ports/stm32f4/common-hal/busio/SPI.c [hunk 1]
```diff
@@ -36,46 +36,35 @@
 #include "supervisor/shared/translate.h"
 #include "common-hal/microcontroller/Pin.h"
 
-STATIC bool reserved_spi[6];
-STATIC bool never_reset_spi[6];
+#define MAX_SPI 6 //TODO; replace this as part of periph cleanup
+#define ALL_CLOCKS 0xFF
+STATIC bool reserved_spi[MAX_SPI];
+STATIC bool never_reset_spi[MAX_SPI];
```
Comment (dhalbert) [inline ports/stm32f4/common-hal/busio/SPI.c]: Could you add a comment that SPI1 corresponds to `reserved_SPI[0]`, etc.?

File: ports/stm32f4/common-hal/busio/SPI.c [hunk 2]
```diff
@@ -412,4 +318,46 @@ uint8_t common_hal_busio_spi_get_phase(busio_spi_obj_t* self) {
...
+    #ifdef SPI4
+    if (mask & 1<<3) __HAL_RCC_SPI4_CLK_DISABLE();
+    #endif
+    #ifdef SPI5
+    if (mask & 1<<4) __HAL_RCC_SPI5_CLK_DISABLE();
+    #endif
+    #ifdef SPI6
+    if (mask & 1<<5) __HAL_RCC_SPI6_CLK_DISABLE();
+    #endif
 }
```
Comment (dhalbert) [inline ports/stm32f4/common-hal/busio/SPI.c]: missing newline at end of file
