### PR TITLE
STM32: Fix Meowbit startup and associated bugs

### LINKED ISSUE #3314: STM32: Meowbit does not start
On the main branch, the Meowbit encounters an issue related to `SysTick->CTRL` at startup during clock configuration, and unexpectedly enters the reset handler before any code can execute. Not yet confirmed whether this occurs across all F401 boards or potentially the rest of the access line. 

Tested with code starting at the default address, so the issue is known to not be related to the Meowbit bootloader.

### PR DESCRIPTION
**Pull request by hierophect**
This PR issues a number of bugfixes related to the Meowbit STM32F401 development board. These include:

- Meowbit configuration file was incorrectly altered to include a low speed oscillator (LSE) resulting in a looping hang at startup. Fixed by removing this reference. 
- In general, boards with a LSE configuration problem would unsuccessfully attempt to auto-recover, making an already confusing problem worse. This "feature" has been removed.
- A null pointer dereference in `common_hal_pulseio_pwmout_deinit` was causing a hardfault during release_displays. Fixed by moving things around and giving myself a nice hard facepalm. 
- `auto_brightness` was set to true in the board_init setup of the Meowbit's TFT screen, which was disabling the screen backlight. This may have been changed behavior from the initial implementation, since this didn't seem to be a problem then. Fixed by setting auto_brightness to false.

Regarding the LSE config problem, I considered adding a new safe mode category to contain issues with a board config, but quickly found that issues in the clock setup are so pervasive and confusing that any form of recovery or error management is probably misguided, especially for a theoretical audience of "board developers who mess up their clock settings and also don't have a debugger". As replacement, any issues in clock setup hang indefinitely in the config function for easy tracing with GDB.

Resolves #3314, and provides final wrap-up to #2702. Help testing would be greatly appreciated from anyone who has a Meowbit handy, I don't believe most of the usual core reviewers have them.

### CODE REVIEW

**Comment by tannewt** [comment]
@jepler Mind reviewing this?

File: ports/stm/common-hal/pwmio/PWMOut.c [hunk 1]
```diff
@@ -239,13 +239,14 @@ void common_hal_pwmio_pwmout_deinit(pwmio_pwmout_obj_t* self) {
         HAL_TIM_PWM_Stop(&self->handle, self->channel);
     }
     reset_pin_number(self->tim->pin->port,self->tim->pin->number);
-    self->tim = NULL;
 
     //if reserved timer has no active channels, we can disable it
     if (!reserved_tim[self->tim->tim_index - 1]) {
         tim_frequencies[self->tim->tim_index - 1] = 0x00;
         stm_peripherals_timer_free(self->handle.Instance);
     }
```
Comment (jepler) [inline ports/stm/common-hal/pwmio/PWMOut.c:247]: I am disappointed that gcc did not show a diagnostic for this.  Amazing!  glad you found it.
