### PR TITLE
Use only DMA0 for PIO background read/write

### LINKED ISSUE #9868: PicoDVI crashes in CircuitPython 9.2.1
### CircuitPython version

```python
Adafruit CircuitPython 9.2.1 on 2024-11-20; Raspberry Pi Pico 2 with rp2350a
```

### Code/REPL

```python
import board
import picodvi
import framebufferio
import displayio
displayio.release_displays()
# Setup for Raspberry Pi Pico 2 - RP2350 - with DVI_Sock installed
fb = picodvi.Framebuffer(320, 240, clk_dp=board.GP14, clk_dn=board.GP15,
                                   red_dp=board.GP12, red_dn=board.GP13,
                                   green_dp=board.GP18, green_dn=board.GP19,
                                   blue_dp=board.GP16, blue_dn=board.GP17,
                                   color_depth=16)
# Boom!                                   
display = framebufferio.FramebufferDisplay(fb)
```

### Behavior

CircuitPython core code crashed hard. Whoops!
Hard fault: memory access or instruction error.

### Description

The latest PicoDVI core library crashes with CircuitPython 9.2.1 on RP2350

Running the HSTX DVI demo code (Display Ruler) works fine on CircuitPython 9.2.0, but crashes on CircuitPython 9.2.1

To replicate on Raspberry Pi Pico 2 with DVI_Sock: 
- Install  CircuitPython 9.2.0 - adafruit-circuitpython-raspberry_pi_pico2-en_US-9.2.0.uf2
- Upload demo code from HSTX_to_DVI_Breakout_Example.zip
- Change pins used in Framebuffer - see above code
-> Runs fine
- Install  CircuitPython 9.2.1 -  adafruit-circuitpython-raspberry_pi_pico2-en_US-9.2.1.uf2
-> Crashes hard

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #9868

Changes PIO background read/write to use only DMA0, not DMA1. This is a minimal change that does not change the current use of a static IRQ handler in `ports/raspberrypi/audio_dma.c`. It reverts to using only DMA0, and uses two `background_pio...` arrays to distinguish between read and write. `picodvi` now works again.

If this works, then I can explore using `irq_add_shared_handler()` as discussed in #9868.

@timchinowsky I tried to test this using a loopback test from https://github.com/timchinowsky/tac5/blob/main/README.md. But those tests as written use a `test=` arg which is no longer present. Could you test this (and update the loopback tests)? Thanks.

### CODE REVIEW

**Comment by timchinowsky** [comment]
Great, thanks for these changes, and sorry about the broken tests, I will get them going.

**Comment by relic-se** [comment]
@dhalbert The `pio_i2s` library relies on the background read and write features as well. The examples within that library should work as a test for these updates as well. https://github.com/relic-se/CircuitPython_PIO_I2S/tree/master/examples

**Comment by dhalbert** [comment]
@relic-se Would you be willing to test the artifact builds here with those examples? Maybe if you are already set up to do so.

**Comment by dhalbert** [comment]
@relic-se if you could describe how to set up a simple test, that would be great. I see the examples programs in the library, but I'm not sure how to set them up to actually send data and test the functionality, in the simplest way possible. For instance, I'm not sure if I need to connect an I2s mic and amp to verify that it works, or whether some loopback test could be set up.

**Comment by relic-se** [comment]
@dhalbert Here's a basic loopback test: https://gist.github.com/relic-se/b90aae77ec4fccb7b03826007b0e41b3. I haven't gotten around to building the fork of this PR, but I've tested it on v9.2.3 using an RP2040-Zero.

File: ports/raspberrypi/audio_dma.c [hunk 1]
```diff
@@ -478,27 +478,13 @@ void __not_in_flash_func(isr_dma_0)(void) {
             dma->channels_to_load_mask |= mask;
             background_callback_add(&dma->callback, dma_callback_fun, (void *)dma);
         }
-        if (MP_STATE_PORT(background_pio)[i] != NULL) {
-            rp2pio_statemachine_obj_t *pio = MP_STATE_PORT(background_pio)[i];
+        if (MP_STATE_PORT(background_pio_read)[i] != NULL) {
+            rp2pio_statemachine_obj_t *pio = MP_STATE_PORT(background_pio_read)[i];
             rp2pio_statemachine_dma_complete_write(pio, i);
```
Comment (relic-se) [inline ports/raspberrypi/audio_dma.c:483]: This should be `rp2pio_statemachine_dma_complete_read`.

File: ports/raspberrypi/common-hal/rp2pio/StateMachine.c [hunk 2]
```diff
@@ -1393,9 +1393,9 @@ bool common_hal_rp2pio_statemachine_background_read(rp2pio_statemachine_obj_t *s
     common_hal_mcu_disable_interrupts();
     // Acknowledge any previous pending interrupt
     dma_hw->ints1 |= 1u << channel_read;
-    MP_STATE_PORT(background_pio)[channel_read] = self;
+    MP_STATE_PORT(background_pio_read)[channel_read] = self;
     dma_hw->inte1 |= 1u << channel_read;
```
Comment (relic-se) [inline ports/raspberrypi/common-hal/rp2pio/StateMachine.c:1397]: I believe that these should be `dma_hw->ints0`.

**Review by relic-se — CHANGES_REQUESTED** [review]
I've tested this build using the example provided in the gist above. The program locks up with the following traceback:

```
Traceback (most recent call last):
  File "<stdin>", line 16, in <module>
  File "pio_i2s.py", line 361, in write
  File "pio_i2s.py", line 340, in write_ready
  File "pio_i2s.py", line 316, in _get_write_index
```

The changes in this review result in a functioning test with an error output of 0.

File: ports/raspberrypi/common-hal/rp2pio/StateMachine.c (hunk 2 above)
Comment (dhalbert) [reply ports/raspberrypi/common-hal/rp2pio/StateMachine.c:1397]: Thanks also for this -- I missed that when changing the arrays.

**Comment by dhalbert** [comment]
@relic-se I added your changes and rebased as well, to catch up. Could you re-test?

**Review by relic-se — APPROVED** [review]
Changes look good and test runs without a hitch!

**Review by jepler — APPROVED** [review]
Thanks! Though I didn't follow the whole discussion this looks sensible and I didn't spot any mistakes. No testing performed.

**Comment by timchinowsky** [comment]
Thanks @relic-se!  Late to the party here, but the loopback tests in https://github.com/timchinowsky/tac5/blob/main/README.md now run as well.
