### PR TITLE
Fix for neopixels on <100MHz STM32 boards

### LINKED ISSUE #2346: STM32: incorrect neopixel timings on 84MHz boards
Neopixel library on the Pyb Nano and STM32F411 Discovery outputs incorrect Neopixel timings (1.5us period). Should be examined alongside the F405 existing implementations. 

@dhalbert may be related to your issue on the dud Feather F405 you were working with. If you recap on your problem here in this issue, I'll keep an eye out for any possible connections.

### PR DESCRIPTION
**Pull request by hierophect**
Unlike the Atmel and NRF ports, the STM32F series has many different max CPU speeds across the starter, foundation and advanced lines. At lower CPU speeds, the previous neopixel code encounters an issue where the cycle time required to change a GPIO pin begins to approach the maximum allowable logic high period for a neopixel 0 bit. This results in the neopixel outputting a strong white as every bit is evaluated as 1 rather than 0. 

I had hoped to replace the system with a weighted one, where the processor cycles needed to change the GPIO pins would be subtracted from the timing, making timing consistent across all frequencies. Unfortunately, I haven't managed to get a fully dynamic system granular enough to be workable. In lieu of writing the whole thing in assembly, I've just shuffled the timing enough to hit acceptable timing across most frequencies. It should work on any ST chip higher than 84MHz, and is protected against optimization differences. 

As a side note, if anyone's used the `ARDUINO_ARCH_ARDUINO_CORE_STM32` code [here](https://github.com/adafruit/Adafruit_NeoPixel/blob/9cf5e96e8f436cc3460f6e7a32b20aceab6e905c/Adafruit_NeoPixel.cpp#L1902), I'd be interested to know if it works, since I don't see how the theoretical timings it uses could cooperate with the 0.22us cycle time required for the functions it uses without added trickery. It might provide some insight on this issue. 

Resolves #2346. @dhalbert, maybe you could also give it a shot on your dud feather and see if it helps at all? 

Bin for Feather below, but it won't do anything other than not break - will be more relevant once #2315 passes review. Also applies to the F411 Discovery, if anyone else has one. 
[firmware.bin.zip](https://github.com/adafruit/circuitpython/files/3918641/firmware.bin.zip)

### CODE REVIEW

File: ports/stm32f4/common-hal/neopixel_write/__init__.c [hunk 1]
```diff
@@ -63,23 +68,26 @@ void common_hal_neopixel_write (const digitalio_digitalinout_obj_t* digitalinout
...
     DWT->CYCCNT = 0;
 
     for(;;) {
+        cyc = (pix & mask) ? t1 : t0;
         start = DWT->CYCCNT;
         LL_GPIO_SetOutputPin(p_port, p_mask);
-        cyc = (pix & mask) ? t1 : t0;
-        while(DWT->CYCCNT - start < cyc);
+        while((DWT->CYCCNT - start) < cyc) {
+            __asm__ __volatile__("nop");
```
Comment (tannewt) [inline ports/stm32f4/common-hal/neopixel_write/__init__.c]: Why have nop here? Doesn't it just make your single loop iteration slower and therefore less granular?

Comment (hierophect) [reply ports/stm32f4/common-hal/neopixel_write/__init__.c]: Not having it here would cause the compiler to optimize the loop out under certain settings. For a while having Os optimization would cause the entire board to hang, and I never quite figured that out. But I can revisit removing these if you think it'd provide benefits.

Comment (tannewt) [reply ports/stm32f4/common-hal/neopixel_write/__init__.c]: Isn't `DWT->CYCCNT` a volatile read? It shouldn't be optimized out then.

Comment (hierophect) [reply ports/stm32f4/common-hal/neopixel_write/__init__.c]: That's a good point. I'm not sure what the optimizer was doing in that case then, it was definitely causing some weird timing when I was varying between different settings. But testing the latest version with them gone seems to work fine, so I'll remove them.

File: ports/stm32f4/common-hal/neopixel_write/__init__.c [hunk 2]
```diff
@@ -40,6 +42,9 @@ uint32_t next_start_tick_us = 1000;
 #define MAGIC_800_T0H  2800000  // ~0.36 us -> 0.44 field
 #define MAGIC_800_T1H  1350000  // ~0.74 us -> 0.84 field
```
Comment (tannewt) [inline ports/stm32f4/common-hal/neopixel_write/__init__.c]: Did you test this after you removed the nops? I'd expect it to change the timing slightly (more so on the slower clock speeds.)

Comment (hierophect) [reply ports/stm32f4/common-hal/neopixel_write/__init__.c]: Yes, they're still within tolerance - works on the PYB Nano, Discovery. I'll give dynamic code another shot once the F401 gets added, since I'll have 3 test cases at that point.
