### PR TITLE
nrf: add SPIM3 support

### LINKED ISSUE #1222: SPI + Bluetooth crash nRF52840
Calling the `write()` method of an SPI object while Bluetooth is active crashes the firmware. 

Here is a minimal code that reproduces the issue:

```python
import board
import busio
from ubluepy import Peripheral

p = Peripheral()
p.advertise()

spi = busio.SPI(board.P0_22, MOSI=board.P1_00)
while not spi.try_lock():
    pass
spi.write(bytes([0xff]))
```

If you comment out the last line (the call to `spi.write()`), then it doesn't crash anymore. Tested on the nRF52840 USB Dongle.

### LINKED ISSUE #2595: nrf: Implement 32MHz SPIM3
Currently we don't use SPIM3 on nrf builds even though it's the only SPIM that provides 32MHz. The peripheral has hardware bugs which must be worked around.

Fixing this will fix #1222.
Also  https://github.com/adafruit/Adafruit_nRF52_Arduino/issues/364

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #2595. 
Fixes #1222.

- Enable SPIM3 support on nRF52840. SPIM3 is 32MHz, other SPIM's are 8MHz. SPIM3 is buggy and requires its own 8kB RAM block when transmitting to avoid corrupted data.
- The first SPI allocated is SPIM3. This is now noted in the doc in `shared-bindings/busio/SPI.c`. This means an onboard display will get to use SPIM3.
- Two I2C's are now available on all nRF boards because we now can use SPIM0/TWIM0  and SPIM1/TWIM1 for I2C, with SPIM2 and SPIM3 for SPI.
- Fixed common_hal SPI polarity and phase routines to return correct values, even though they aren't currently used.

Tested on a CLUE with a slideshow program. It's hard to see the speedup, but it was already fast. I verified in the debugger that it was using SPIM3 for the display.

Also tested on a Feather nRF52840 with a Saleae to verify that SPIM3 is allocated and that it is running at 32MHz.

### CODE REVIEW

File: ports/nrf/common-hal/busio/SPI.c [hunk 1]
```diff
@@ -224,21 +232,36 @@ void common_hal_busio_spi_unlock(busio_spi_obj_t *self) {
...
     const uint32_t max_xfer_size = self->spim_peripheral->max_xfer_size;
     const uint32_t parts = len / max_xfer_size;
     const uint32_t remainder = len % max_xfer_size;
 
     for (uint32_t i = 0; i < parts; ++i) {
-        const nrfx_spim_xfer_desc_t xfer = NRFX_SPIM_XFER_TX(data + i * max_xfer_size, max_xfer_size);
+        uint8_t *start = (uint8_t *) (data + i * max_xfer_size);
+        if (is_spim3) {
+            // If SPIM3, copy into unused RAM block, and do DMA from there.
+            memcpy(spim3_transmit_buffer, start, max_xfer_size);
```
Comment (tannewt) [inline ports/nrf/common-hal/busio/SPI.c]: I wonder if we should put the displayio buffer in this ram as well. That way we could check the location of the buffer and skip the memcpy.

Comment (dhalbert) [reply ports/nrf/common-hal/busio/SPI.c]: That sounds like a good idea, since the 8kB is otherwise wasted. In fact, in the current implementation, we are only using the first 8 bytes or something like that. But we have to allocate the whole 8kB because otherwise there could be errors caused by contention on the block.

The buffer would be in that space conditionally; you'd check that the SPIM is SPIM3 when making the decision.

**Comment by hathach** [comment]
@dhalbert I saw an incredibly speed up with display when using SPIM3 @ 32MHz when getting it on to Arduino. Here is the TFT speed between nrf52840 (left) vs Samd51 (right). The trick is bulk transferring the data ( a frame line or so). If doing small chunk, DMA actually slower than non-dma mode. Just my two cents.  
https://photos.app.goo.gl/T37kjetpKzQ7oDnz7
