### PR TITLE
Track unadjusted PWM duty cycle to avoid accumulating conversion errors

### LINKED ISSUE #2086: PWMOut failed when changing frequency in an infinite loop
I try to understand why it failed to generate PWM signals after 30+ seconds or so on my ATSAMD21G18. Other functions (such as print) seem to work just fine but just the PWM function stop generate PWM signals. 

I did test it when changing duty_cycle in an infinite loop, and it works just fine. Not sure why it causes a problem with switching frequency. Any thought?

The code is pretty simple as:
```    
import time
import board
import pulseio

PIN_Test = pulseio.PWMOut(board.A4, frequency=5000, duty_cycle=2 ** 15,  variable_frequency=True)

while True:
   FRE = random.randint(100, 200)
   COUNT = random.randint(1, 20)
    while COUNT >0:
        COUNT -=1
        PIN_Test.frequency=FRE
        print("NEW COUNT = ", COUNT, "at FRE =", FRE)
```

### PR DESCRIPTION
**Pull request by theacodes**
Fixes #2086

When the frequency of a `PWMOut` is changed it re-sets the PWM's duty cycle as
well, since the registers have to be re-calculated based on the new frequency.
Unfortunately, `common_hal_pulseio_pwmout_get_duty_cycle`
will return a value very close to, but not exactly, the value passed to `common_hal_pulseio_pwmout_set_duty_cycle`. If the frequency is modified
without the calling code also re-setting the duty cycle then the duty cycle
will decay over time. This fixes that problem by tracking the unadjusted duty
cycle and re-setting the duty cycle to that value when the frequency is changed.

### CODE REVIEW

**Comment by theacodes** [comment]
I haven't had a chance to test this out on real hardware yet, but if someone wants to beat me to it by all means. :)

**Comment by theacodes** [comment]
Tested on an Adafruit Gemma M0.

Test code:

```python
import time
import board
import pulseio

duty_cycle = 32768
pwm = pulseio.PWMOut(board.A2, frequency=5000, duty_cycle=duty_cycle,  variable_frequency=True)

for _ in range(100000):
    pwm.frequency = 150

print("Set duty cycle: ", duty_cycle, ", Read duty cycle: ", pwm.duty_cycle)
    
```

Reproduction of original issue:

```
Adafruit CircuitPython 5.0.0-alpha.4-241-g84c0d6cdf on 2019-10-21; Adafruit Gemma M0 with samd21e18

Set duty cycle:  32768, Read duty cycle:  0
```

With the changes in this PR duty cycle does not fall to zero despite repeated frequency changes:

```
Adafruit CircuitPython 5.0.0-alpha.4-242-gcf8e3c24f on 2019-10-22; Adafruit Gemma M0 with samd21e18

Set duty cycle:  32768, Read duty cycle:  32767
```

**Comment by theacodes** [comment]
Seems like the CI failures are due to DNS flakiness in the CI system. This should be ready for review. :)

File: ports/atmel-samd/common-hal/pulseio/PWMOut.c [hunk 1]
```diff
@@ -322,6 +323,13 @@ void common_hal_pulseio_pwmout_deinit(pulseio_pwmout_obj_t* self) {
 }
 
 extern void common_hal_pulseio_pwmout_set_duty_cycle(pulseio_pwmout_obj_t* self, uint16_t duty) {
+    // Store the unadjusted duty cycle. It turns out the the process of adjusting and calucating
+    // the duty cycle here and reading it back is lossy - the value will decay over time.
+    // Track it here so that if frequency is changed we can use this value to recalcuate the
```
Comment (dhalbert) [inline ports/atmel-samd/common-hal/pulseio/PWMOut.c]: "recalculate"

File: ports/atmel-samd/common-hal/pulseio/PWMOut.c [hunk 2]
```diff
@@ -322,6 +323,13 @@ void common_hal_pulseio_pwmout_deinit(pulseio_pwmout_obj_t* self) {
 }
 
 extern void common_hal_pulseio_pwmout_set_duty_cycle(pulseio_pwmout_obj_t* self, uint16_t duty) {
+    // Store the unadjusted duty cycle. It turns out the the process of adjusting and calucating
```
Comment (dhalbert) [inline ports/atmel-samd/common-hal/pulseio/PWMOut.c]: "calculating"

**Comment by theacodes** [comment]
> I think it might be worth documenting in shared-bindings/pulseio/PWMOut.c that .duty_cycle and .frequency return the actual values, which may differ from the requested values due to granularity. Also say something like, "if frequency is changed, the duty cycle is recomputed using the original requested value".

Done in 678294875
