### PR TITLE
Fix setup of Espressif PinAlarms

### LINKED ISSUE #6994: PinAlarm not working properly with value=True
### CircuitPython version

```python
Adafruit CircuitPython 8.0.0-beta.1-6-gb62f8b35e on 2022-10-04; Adafruit Feather ESP32S2 with ESP32S2
```

### Code/REPL

```python
import board
import alarm

print("Alarm:", alarm.wake_alarm)

pin_alarm = alarm.pin.PinAlarm(pin=board.D12, value=True, pull=True)
print("Entering deep sleep.")
alarm.exit_and_deep_sleep_until_alarms(pin_alarm)
```

### Behavior

While connected to the serial console, it prints `Entering deep sleep.` and then nothing. The `Pretending to deep sleep....` message never shows up, and you can no longer interact with the serial console with CTRL+D/C. If you want to save and reload your code, you must press the reset button to do so.

### Description

If you connect the trigger pin to GND before reloading the board, and then connect it to 3V, it at least wakes up the board when connected to 3V, but it still seems to be a bit wonky.

If you update `value` to `False`, the issue is resolved, and everything responds appropriately. 

### Additional information

Narrowed the issue down to this after testing #6676 (the TimeAlarm+PinAlarm issue was a red herring, they work fine together.)

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #6994.
---
- Code to wait for a pull to happen was wrong -- it only waited in one direction, and it waited essentially forever. Not a good idea anyway, since the pin might be tied firmly to one value or the other. Instead, add a brief delay after setting all pulls.
- Make sure RTC is powered up during sleep.
- Unrelated corrections. to Metro ESP32-S2 debug UART pins.

### CODE REVIEW

File: ports/espressif/common-hal/alarm/pin/PinAlarm.c [hunk 1]
```diff
@@ -231,6 +232,7 @@ void alarm_pin_pinalarm_set_alarms(bool deep_sleep, size_t n_alarms, const mp_ob
             if (esp_sleep_enable_ext1_wakeup(1ull << low_pins[1], ESP_EXT1_WAKEUP_ALL_LOW) != ESP_OK) {
                 mp_raise_ValueError(translate("Can only alarm on RTC IO from deep sleep."));
             }
+            esp_sleep_pd_config(ESP_PD_DOMAIN_RTC_PERIPH, ESP_PD_OPTION_ON);
```
Comment (jepler) [inline ports/espressif/common-hal/alarm/pin/PinAlarm.c:235]: does this need to be done in the "low_count > 0" (i.e., == 1) case? I don't know what the call does.

.. apparently, no, this is specific to ESP_EXT1_WAKEUP. https://docs.espressif.com/projects/esp-idf/en/latest/esp32s2/api-reference/system/sleep_modes.html#external-wakeup-ext1 assuming all esp32/s2/s3 are identical. I just checked the one page.

**Review by jepler — APPROVED** [review]
no testing performed but the basic change makes sense. waiting forever for a pin to reach a particular status doesn't seem right. 50ms should be generous for almost any RC constant of a pulled I/O pin.

File: ports/espressif/common-hal/alarm/pin/PinAlarm.c (hunk 1 above)
Comment (dhalbert) [reply ports/espressif/common-hal/alarm/pin/PinAlarm.c:235]: RIght, I checked that. I'm not sure this is necessary, because there is some "automatic" setting of these power domains based on what is going on elsewhere, but I think it's belt-and-suspenders.

**Comment by dhalbert** [comment]
I will merge this now in prep for a beta.4 fairly soon. @kattni you can test at your leisure.
