### PR TITLE
STM: off-by-one TIMx reference; other code cleanup and minor fixes

### LINKED ISSUE #7040: Some PWMOut pins on STM32F405 run at half frequency
True in 8.0.0-beta.1 on Feather STM32F405.
```py
import pwmio, board
a1 = pwmio.PWMOut(board.A1, duty_cycle=32768, frequency=1000)
d5 = pwmio.PWMOut(board.D5, duty_cycle=32768, frequency=1000)
d6 = pwmio.PWMOut(board.D6, duty_cycle=32768, frequency=1000)
d9 = pwmio.PWMOut(board.D9, duty_cycle=32768, frequency=1000)
d10 = pwmio.PWMOut(board.D10, duty_cycle=32768, frequency=1000)
a3 = pwmio.PWMOut(board.A3, duty_cycle=32768, frequency=1000)
while True:
    pass
```
A1 runs at 500 Hz; D5 runs at the (proper) 1 kHz; another one runs at 2kHz; others are OK.

Thanks to SleeplessHeart from https://forums.adafruit.com/viewtopic.php?p=943799.

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #7040.

- `stm_peripherals_timer_get_source_freq()` was off by one in its TIMx numbering assumption, causing incorrect lookups of some timer frequencies.
- In `PulseIn.c`, timer clock reset was being done with an integer instead of a bitmask. Noticed this while looking for other manifestations of the previous bug.
- Added some logic to `stm_peripherals_timer_get_source_freq()` to handle other variants of STM chips. Not tested, but would have been wrong otherwise.
- Reworked timer assignment code in `PWMOut` a bit for clarity and to make any returned errors more accurate.

### CODE REVIEW

**Review by tannewt — APPROVED** [review]
Thank you!

File: ports/stm/common-hal/pwmio/PWMOut.c [hunk 1]
```diff
@@ -62,13 +63,10 @@ STATIC bool timer_get_optimal_divisors(uint32_t *period, uint32_t *prescaler,
...
 
 void pwmout_reset(void) {
-    uint16_t never_reset_mask = 0x00;
     for (int i = 0; i < TIM_BANK_ARRAY_LEN; i++) {
         if (!never_reset_tim[i]) {
-            reserved_tim[i] = 0x00;
-            tim_frequencies[i] = 0x00;
-        } else {
-            never_reset_mask |= 1 << i;
+            tim_channels_taken[i] = 0x00;
```
Comment (jepler) [inline ports/stm/common-hal/pwmio/PWMOut.c:68]: this doesn't actually modify any of the registers, so won't the pwm peripheral keep doing whatever it was doing before reset()?  Are we depending on some other way of stopping the physical output on the pin, like setting the pin's function to gpio or disabled? This might merit a comment.

**Review by jepler — COMMENTED** [review]
I have one note, maybe an added comment would be helpful.

Not sure what's going on with github, I don't have the usual approve/request changes/just comment buttons to select the 'result' of my review.

**Comment by jepler** [comment]
oh, because the PR had already been merged, that's why.

File: ports/stm/common-hal/pwmio/PWMOut.c (hunk 1 above)
Comment (dhalbert) [reply ports/stm/common-hal/pwmio/PWMOut.c:68]: This is really another bug.

Comment (dhalbert) [reply ports/stm/common-hal/pwmio/PWMOut.c:68]: On second thought, the timers are reset by `timers_reset()`, so I think this is OK.
