### PR TITLE
finalisers for SPI; clean up sdcardio; reset all pins after finalisers; avoid USB SD races

### LINKED ISSUE #10680: Enabling microSD and Display on QtPy ESP32-S3 SPI Bus Results in Crash to Safe Mode
### CircuitPython version and board name

```python
Adafruit CircuitPython 10.0.1 on 2025-10-09; Adafruit QT Py ESP32-S3 no psram with ESP32S3
```

### Code/REPL

```python
spi = board.SPI()
i2c = board.STEMMA_I2C()

# Setup SD card
tft_sdcs = board.A3
sdcard = sdcardio.SDCard(spi, tft_sdcs)
vfs = storage.VfsFat(sdcard)
storage.mount(vfs, "/sd")

# Set tft pins for QTPy EYESPI BFF on ESP32-S3
tft_cs = board.TX
tft_dc = board.RX
tft_reset = None
tft_backlight = board.A1 # Jumpered EyeSpy BFF Lite pin to Qt Py pin A1
tft_bpwmfreq = 50000 # Default is 50000
displayio.release_displays()
display_bus = FourWire(spi, command=tft_dc, chip_select=tft_cs, reset=tft_reset)
display = GC9A01A(display_bus, width=240, height=240, backlight_pin=tft_backlight, backlight_pwm_frequency=tft_bpwmfreq)
bg_group = displayio.Group()
```

### Behavior

Immediate crash to safe mode.
```python
You are in safe mode because:
Hard fault: memory access or instruction error
Please file an issue with your program at github.com/adafruit/circuitpython/issues.
Press reset to exit safe mode.
```

### Description

Complete hardware setup includes:

- QT Py ESP32-S3 8MB flash no PSRAM
- QT Py EYESPY BFF
- 1.28 inch round 240x240 TFT display with microSD card reader
- APD59960 light/color/proximity/gesture sensor (connected via STEMMA I2C)

The board does not crash under the following two circumstances:

1.  If I remove the `storage.mount(vfs, "/sd")` command (but, of course, I cannot then use the microSD card).
2. If I keep the `storage.mount(vfs, "/sd")` command but remove everything after it (everything associated with the TFT setup).

Further debugging isolated the crash to when the 
```python
display = GC9A01A(display_bus, width=240, height=240, backlight_pin=tft_backlight, backlight_pwm_frequency=tft_bpwmfreq)
```
is executed (when the `storage.mount(vfs, "/sd")` command is included).

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #10680 and perhaps other issues.

This is a multi-part fix for race conditions occurring on VM shutdown when an SD card mounted in user code is exposed via USB MSC. There can be filesystem operations initiated by the host that are in process when `code.py` ends., which cause crashes or USB disconnects. In the process of debugging this, I found several other things to clean up and add.

### SPI resetting when VM shuts down
Previously, many ports had `spi_reset()` or `reset_spi()` routines that reset all SPI buses that were not persistent when the VM shut down. If there were host-initiated USB MSC operations (usually just reads) on a user-mounted filesystem, these forced resets would interfere with those USB MSC operations, or vice versa. For instance, on Espressif, the forced resets would fail if an SPI operation was in progress.
- Change `busio.SPI()` to have a finaliser. This obviates the need for a global SPI reset.
- Remove all `reset_spi()` and `spi_reset()`. The `common_hal_busio_spi_deinit()` routines take care of all SPI resetting necessary when the finalisers are run. 
- Add `common_hal_busio_spi_mark_deinit()` routines to all `busio.SPI` implementations, and call them as appropriate in the various `SPI.c` files.
- Add a call to `common_hal_busio_spi_mark_deinit()` in ` shared-module/displayio/__init__.c` when a `FourWire` bus is copied. This mimics what was already done for `displayio` I2C bus copies, when `busio.I2C()` was changed to use a finaliser.
- Use dynamically allocated mutexes for SPI locking instead of the previous statically allocated mutexes. This now mimics what is done in the I2C implementation.

### Don't reset pins before finalisers run
`reset_port()` is called in `main.c` before finalisers are run. On all ports, `reset_port()` would call `reset_all_pins()`. However, this meant that SPI pins would get reset while SD card operations might still be in progress, allowing the kind of race conditions described above.
- Move the call to `reset_all_pins()` out of the port-specific `reset_port()` routines, and instead call it in `main.c` _after_ `stop_mp()`, and so therefore after the finalisers run. All ports provide `reset_all_pins()`, so it does not need to be called individually in each port. I was initially thinking about add a `reset_port_after_finalisers()` routine for each port that called `reset_all_pins()`, but this was not necessary.

### `sdcardio` improvements
- Fix signature of `cmd_nodata`, which was `bool` but should have been `int`.
- Return `-MP_EIO` instead of `-EIO` several places. The value is the same.
- Add a `persistent_mount` flag to `sdcardio_sdcard_construct()` to distinguish user-mounted SD cards from automounted SD card mounts that persist across VM's. This flag is used to implement the next item.
- Acquire the SPI lock more carefully in `lock_and_configure()` in `SDCard.c`. Once it has been acquired, check whether the VM is still running and whether the mount is persistent before proceeding. If the mount is not persistent and the VM is no longer running, give up the lock.

### `supervisor/shared/usb/usb_msc_flash.c` fixes
- To be more correct, guard some code with `CIRCUITPY_SDCARD_USB` instead of `CIRCUITPY_SDCARDIO`.
- To be more correct, guard some other code with `#ifdef SDCARD_LUN` instead of `CIRCUITPY_SDCARD_USB`.
-  `get_vfs()` will now check if the LUN passed in is for a user-mounted SD card but the VM is no longer running, and will return NULL. This prevents USB MSC operations that are attempted to be  initiated after the VM starts to shut down. However, there are still races that can happen and the other checks above avoid those races.

### Other
- Add a `bool vm_is_running()` routine, which is `true` when the VM has finished starting up and is set to `false` when it starts to shut down. This supports the "VM is running" checks mentioned above.  The flag is set and cleared in `main.c`. 
- For Espressif I2C, delete the mutex on deinit. This had been forgotten, and I stumbled on it it while studying the I2C finaliser implementation.

---

This is a draft to start with because I need to test the non-Espressif ports for SPI issues, especially with SD cards, and I can use the PR builds for that testing.

### CODE REVIEW

File: ports/broadcom/common-hal/busio/SPI.c [hunk 1]
```diff
@@ -33,28 +33,6 @@ static SPI1_Type *aux_spi[NUM_SPI] = {NULL, SPI1, SPI2};
 static bool never_reset_spi[NUM_SPI];
```
Comment (tannewt) [inline ports/broadcom/common-hal/busio/SPI.c]: I think you  can remove never_reset machinery for SPI now too since there is no bulk reset.

File: ports/espressif/supervisor/port.c [hunk 2]
```diff
@@ -417,7 +414,7 @@ void reset_to_bootloader(void) {
 }
 
 void reset_cpu(void) {
-    #if CIRCUITPY_DEBUG
+    #if CIRCUITPY_DEBUG || 1
```
Comment (tannewt) [inline ports/espressif/supervisor/port.c]:
```suggestion
    #if CIRCUITPY_DEBUG
```

Comment (dhalbert) [reply ports/espressif/supervisor/port.c]: fixed :)

File: ports/broadcom/common-hal/busio/SPI.c (hunk 1 above)
Comment (dhalbert) [reply ports/broadcom/common-hal/busio/SPI.c]: Thanks. I forgot this the last time I added finalisers to something as well.

**Comment by dhalbert** [comment]
Tested on Metro ESP32-S3, Fruit Jam, Feather nRF52840 with AdaLogger FeatherWing, ESP32-S3 TFT Feather with AdaLogger, PyPortal. All mounted SD card manually except for Fruit Jam. The USB presentation worked and I was able to read files. I could write files when the SD card was mounted `readonly=True`. No crashes. The display worked fine on the TFT Feather (SPI) and on the PyPortal (not SPI).

Ready for approval to merge.
