### PR TITLE
Fix cardputer boot loop, and do some cleanup

### LINKED ISSUE #10590: M5Stack Cardputer bootloop with CircuitPython 10.0.0-beta.2
### CircuitPython version and board name

```python
Adafruit CircuitPython 10.0.0-beta.2 on 2025-07-31; M5Stack Cardputer with ESP32S3
Board ID:m5stack_cardputer
```

### Code/REPL

```python
No code
```

### Behavior

With ```Adafruit CircuitPython 9.2.0 on 2024-10-28; M5Stack Cardputer with ESP32S3``` the cardputer v1.0 (S3) and v1.1 (S3A) work fine.

But when upgraded to 10.0.0-beta2, with Open Installer, the board bootloop with the screen blinking with just the boot message, never appearing as a USB device (no CIRCUITPY drive).

### Description

Image

### Additional information

This has been reported by todbot on 22/07/2025 08:32 with 10.0.0-beta0
And confirmed by me (David Glaude) 02/08/2025 14:49 on discord.

Depending scenario the bootloop display (blinking):
* Just the circuitpython logo
* Random pixels color
* The boot screen (just after flashing)

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #10590

Detailed changes:
- For `cardputer_keyboard.c`, allocate `DemuxKeyMatrix` it creates and the objects it holds (all the way down) on the port heap, because it lives past VM's.
- To do the above, add support for non-VM heap for `DemuxKeyMatrix` and the `keypad` allocations it needs by passing an arg `use_gc_allocator`, as is done in `lvfontio`.
- Add `mp_obj_port_malloc()`, `mp_obj_port_malloc_var()`, `mp_obj_new_port_tuple()`, all of which allocate on the port heap, not the VM heap.
- Add `port_malloc_zero()`, because `port_malloc()` did not zero out its allocation, unlike VM heap allocations. I got caught by this.
- Move `port_gc_collect()` from `main.c` to `supervisor/port.c` for consistency. This function is not actually used by anyone, but I was considering using it.
-~~Add an `MP_WEAK` `mp_board_init()`, for board-specific initializations needed when a VM starts. Also considered, but not used. Added anyway for possible future use.~~
- ~~Add an `MP_WEAK` `board_gc_collect()`, for board-specific gc. Not used.~~
- Don't duplicate keyboard code between `boards/m5stack_cardputer` and `boards/m5stack_cardputer_ros`. Instead, add a `ports/espressif/module` directory for this code, in the style of a port-specific `module` directory, like the port-specific `bindings` directories.

My original approach to this was to make the `cardputer_keyboard` object be allocated when the VM started up. That  required less pervasive changes, and it worked fine, _except_ for the `Press any key...` when the VM finished. So I had to make it live across VM's.

I tested and @dglaude also tested (thanks!).

### CODE REVIEW

**Comment by dhalbert** [comment]
I cherry-picked two commits from https://github.com/micropython/micropython/pull/17269/ to fix a gcc 15 build problem on Windows.

File: supervisor/shared/board.c [hunk 1]
```diff
@@ -44,3 +44,11 @@ MP_WEAK void board_deinit(void) {
...
 MP_WEAK void reset_board(void) {
 }
+
+// Do-nothing so not all boards need to provide this function.
+MP_WEAK void mp_board_init(void) {
+}
+
+// Do-nothing so not all boards need to provide this function.
+MP_WEAK void board_gc_collect(void) {
+}
```
Comment (tannewt) [inline supervisor/shared/board.c]: Do you actually need these? I'd love to move away from MP_WEAK since these can be used even when not expected. In other words, the compiler doesn't check for correctness here. A #define to enable the function would be compile checked.

**Review by tannewt — CHANGES_REQUESTED** [review]
One minor thing. Thanks!

File: supervisor/shared/board.c (hunk 1 above)
Comment (dhalbert) [reply supervisor/shared/board.c]: I don't need them, so I'll just remove them. I just spent the time figuring out where to put them, but I can come back to the commit to find that.

 I left `port_gc_collect()` because it was already there.

I'll open an issue about replacing `MP_WEAK` functions with some guards instead. Did you mean that one might accidentally replace a weak function by mistake?

Comment (tannewt) [reply supervisor/shared/board.c]: > Did you mean that one might accidentally replace a weak function by mistake?

Nope, you may *think* you are overriding one but don't actually. So, it'll compile and link but not run the implementation you expected. (Lots of IDF issues for us were this.)
