### PR TITLE
espressif: fix returning ping time and pinging too often

### LINKED ISSUE #7940: ping too frequently results in resource exhaustion, exception
### CircuitPython version

```python
Adafruit CircuitPython 8.1.0-beta.2-24-gd2aca7eba0-dirty on 2023-05-05; ESP32-S3-DevKitC-1-N8R2 with ESP32S3
Board ID:espressif_esp32s3_devkitc_1_n8r2
UID:866B3BD27A8F
```

### Code/REPL

```python
import time
import wifi
from secrets import secrets

DELAY = 0.5  # this is fine, but lower values lead to exceptions after a few pings

wifi.radio.connect(secrets['ssid'], secrets['password'])
while True:
    print(f"LAN ping: {wifi.radio.ping(wifi.radio.ipv4_gateway)}s")
    time.sleep(DELAY)
```

### Behavior

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
espidf.IDFError: Generic Failure
```

### Description

The esp-idf implementation of ping creates a task which actually sends and receives the ping packets.

When `esp_ping_delete_session` is called, the underlying resources are not immediately freed. Instead, this waits until a (hard coded) 1 second delay expires in the ping task, which then checks a flag, frees resources, and terminates itself.

### Additional information

Before #7938 this led to a hard crash and entry into safe mode(#5980), as the return value of `esp_ping_new_session` wasn't checked. Now that the return value is checked, there's a (recoverable, potentially) exception. That's an improvement on the status quo ante but it'd be nice if ping did not have this resource exhaustion problem. This likely means creating our own ping implementation, rather than using esp-idf's.

### LINKED ISSUE #9348: ping does not return a time (always says 0.0 or None)
### CircuitPython version

```python
Adafruit CircuitPython 9.1.0-beta.3 on 2024-05-22; Ai Thinker ESP32-CAM with ESP32
```

### Code/REPL

```python
>>> import time
>>> import wifi
>>> import ipaddress
>>> ip1 = ipaddress.ip_address("196.1.56.26") # this is deliberately a very slow server in S.A.
>>> print(wifi.radio.ping(ip1))
None
>>> print(wifi.radio.ping(ip1,timeout=2))
0.0
>>> ip1 = ipaddress.ip_address("1.1.1.1")
>>> print(wifi.radio.ping(ip1))
0.0
>>> print(wifi.radio.ping(ip1))
0.0
>>>
```

### Behavior

prints 0.0

### Description

should print times - here's what linux does:-

```
$ ping -c 1 1.1.1.1
PING 1.1.1.1 (1.1.1.1) 56(84) bytes of data.
64 bytes from 1.1.1.1: icmp_seq=1 ttl=58 time=476 ms

--- 1.1.1.1 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 476.281/476.281/476.281/0.000 ms
```

```
$ ping -c 1 196.1.56.26
PING 196.1.56.26 (196.1.56.26) 56(84) bytes of data.
64 bytes from 196.1.56.26: icmp_seq=1 ttl=45 time=1185 ms

--- 196.1.56.26 ping statistics ---
1 packets transmitted, 1 received, 0% packet loss, time 0ms
rtt min/avg/max/mdev = 1184.691/1184.691/1184.691/0.000 ms

```

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #9348 
- Ameliorates #7940, but that issue will remain open.

The ping time gets lost if it's not retrieved during a ping callback, because the storage used is freed quite early. Set up a callback to retrieve the time instead of fetching it directly.

I prevented the errors seen in  #7940 while I was in the code, by waiting a couple of seconds and trying again if `esp_ping_new_session()` fails. Interestingly, I had to wait at least two seconds, not the one second that is the task timeout.

@gitcnd

### CODE REVIEW

File: ports/espressif/common-hal/wifi/Radio.c [hunk 1]
```diff
@@ -532,32 +532,59 @@ void common_hal_wifi_radio_set_ipv4_address_ap(wifi_radio_obj_t *self, mp_obj_t
...
+        // Wait for old task to go away and then try again.
+        // Empirical testing shows we have to wait at least two seconds, despite the task
+        // having a one-second timeout.
+        common_hal_time_delay_ms(2000);
+        if (mp_hal_is_interrupted()) {
+            return -1;
+        }
+    }
+    CHECK_ESP_RESULT(ret);
+
```
Comment (jepler) [inline ports/espressif/common-hal/wifi/Radio.c:572]: (sorry if this appears twice; github seems to have eaten my comment)

I'm not super confident about this change.

 * I don't relish the idea of explaining to the user: yes, ping takes 2 seconds in time.monotonic but claims the ping response time is 0.1 seconds.
 * esp_ping_new_session might fail for other reasons (e.g., all sockets are in use) and now ping will wait 10 seconds before returning failure. before, it would fail prompt.y

**Review by jepler — COMMENTED** [review]
If others think the change is fine, please go ahead and put it in, but I have misgivings about this change as the way to close #7940.

File: ports/espressif/common-hal/wifi/Radio.c (hunk 1 above)
Comment (dhalbert) [reply ports/espressif/common-hal/wifi/Radio.c]: I've reworked this to wait a maximum of two seconds on failure, and also documented this.

I agree a slow call that returns a fast ping time is weird, but without rewriting the underlying ping implementation (which should probably be done, but I'm not going to do now), I think this is better than the current situation, which also requires explanation.

**Review by bill88t — APPROVED** [review]
I also think quick failures are better than long timeouts.
The code looks good to me. Haven't tested yet.

File: ports/espressif/common-hal/wifi/Radio.c (hunk 1 above)
Comment (dhalbert) [reply ports/espressif/common-hal/wifi/Radio.c]: @jepler Does the second commit alleviate your concerns?

@tannewt How is this PR for you?

**Review by jepler — APPROVED** [review]
it's fine with me, except I'd rather that the issue about espressif ping limitations be updated with new info, rather than being closed by the merge of this PR.

**Comment by dhalbert** [comment]
@jepler Thanks, I have left #7940 open, with a comment.
