### PR TITLE
Fix MDNS crash on S2

### LINKED ISSUE #6186: mDNS safe mode - find
### CircuitPython version

```python
Adafruit CircuitPython 7.3.0-alpha.0-52-g4465adfe0 on 2022-03-21; FeatherS2 with ESP32S2
(this is the version that corresponds to the mDNS merge)
```

### Code/REPL

```python
import wifi
import mdns
from secrets import secrets

print(" Connecting", end="\r")
wifi.radio.connect(secrets['ssid'], secrets['password'])
print(wifi.radio.ipv4_address)

print("Starting mDNS server...")
server = mdns.Server(wifi.radio)
service_types = ("_http", )

protocols = ("_tcp", )
for service_type in service_types:
    print(service_type, end=" ")
    for protocol in protocols:
        print(protocol)
        remote_service_tuple = server.find(service_type=service_type, protocol=protocol, timeout=5)
        for remote_service in remote_service_tuple:
            print(remote_service.hostname, remote_service.instance_name, remote_service.service_type, remote_service.protocol, remote_service.port)
```

### Behavior

The example code probably works in many environments, but Safe Mode occurs when substituting many other service types and protocols. Hypothesis is there are no results for that combination.
```
code.py output:
Connected.    
Starting mDNS server...
_upnp _udp

[tio 21:28:16] Disconnected
[tio 21:28:20] Connected
Running in safe mode! Not running saved code.

You are in safe mode because:
CircuitPython core code crashed hard. Whoops!
Crash into the HardFault_Handler.
Please file an issue with the contents of your CIRCUITPY drive at 
https://github.com/adafruit/circuitpython/issues

Press any key to enter the REPL. Use CTRL-D to reload.
```

### Description

Pattern seems to be Safe Mode when trying to `find` a service type and protocol that do not exist on the network.

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tannewt**
Fixes #6186

### CODE REVIEW

File: ports/espressif/common-hal/mdns/Server.c [hunk 1]
```diff
@@ -117,6 +117,11 @@ mp_obj_t common_hal_mdns_server_find(mdns_server_obj_t *self, const char *servic
         next = next->next;
     }
     mp_obj_tuple_t *tuple = MP_OBJ_TO_PTR(mp_obj_new_tuple(num_results, NULL));
+    // The empty tuple object is shared and stored in flash so return early if
```
Comment (jepler) [inline ports/espressif/common-hal/mdns/Server.c:120]: mp_obj_new_tuple already sets the length to n, so instead of special casing num_results == 0, you can remove the assignment of len below.

**Review by jepler — CHANGES_REQUESTED** [review]

File: ports/espressif/common-hal/mdns/Server.c (hunk 1 above)
Comment (tannewt) [reply ports/espressif/common-hal/mdns/Server.c:120]: I set it to `added` below in case we can make the wrapper objects for all of the results. So, it may be different than the value at alloc time. Want me to make it compare the current len vs added and then set it if different?

Comment (jepler) [reply ports/espressif/common-hal/mdns/Server.c:120]: urp .. tuples are meant to be static in size, I'm not sure of the impact of truncating one after initial allocation. but the tuple at this point is not seen by python code, so it doesn't matter.

**Review by jepler — APPROVED** [review]
thanks!

**Comment by jepler** [comment]
If memory is at a premium, it would be better to change this into an iterator object, even if it's a bit more work. doing this before the next 7.x.0 would be good so that it wasn't an incompatible API change.
