### PR TITLE
Fix memoryview.cast over sliced memoryview

### LINKED ISSUE #4758: memoryview slice+cast has wrong values
On standard Python 3.7,
```
>>> hex(memoryview(b'\1\2\3\4\5\6\7\8')[2:6].cast('i')[0])
'0x6050403'
```
while on circuitpython,
```
Adafruit CircuitPython 6.2.0-rc.0-47-gd6c924449-dirty on 2021-04-03; Adafruit CLUE nRF52840 Express with nRF52840
hex(memoryview(b'\1\2\3\4\5\6\7\8')[2:6].cast('i')[0])
'0x4030201'
```

### PR DESCRIPTION
**Pull request by tannewt**
Fixes #4758

### CODE REVIEW

File: ports/unix/main.c [hunk 1]
```diff
@@ -716,7 +716,7 @@ MP_NOINLINE int main_(int argc, char **argv) {
 }
 
 #if !MICROPY_VFS
-uint mp_import_stat(const char *path) {
+mp_import_stat_t mp_import_stat(const char *path) {
```
Comment (tannewt) [inline ports/unix/main.c:719]: This fixes a compiler warning with GCC13

**Review by jepler — APPROVED** [review]
Thanks! does upstream need this fix too? 

not sure what's going on with the error'd build

**Comment by tannewt** [comment]
> Thanks! does upstream need this fix too?
> 
> not sure what's going on with the error'd build

Nope, you added `.cast()` it isn't upstream.

A retry of the build worked. I think there is a parallelism issue with mg24 builds.
