### PR TITLE
Fix SAMD I2C frequency check

### LINKED ISSUE #6669: 8.0.0-alpha.1 and later: SAMD I2C bus speeds validation broken
SAMD normally forbids I2C bus speeds < 95 kHz. This is working on 7.3.2, but on 8.0.0-alpha.1 and later, the check isn't working, and the actual speed set is way off when a speed <95 is set. True on SAMx5 and SAMD21.

@ladyada reports about 600 kHz speed when set to 30 kHz.

```py
Adafruit CircuitPython 7.3.2 on 2022-07-20; Adafruit PyPortal Titano with samd51j20
>>> 
>>> import board,busio
>>> i2c = busio.I2C(board.SCL, board.SDA, frequency=30000)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ValueError: Unsupported baudrate
```
```py
Adafruit CircuitPython 8.0.0-alpha.1 on 2022-06-09; Adafruit PyPortal Titano with samd51j20
>>> 
>>> import busio,board
>>> i2c = busio.I2C(board.SCL, board.SDA, frequency=30000)
# NOTE NO ERROR
```
Code is https://github.com/adafruit/circuitpython/blob/8b2f0615639a616028803db1f4a96614ed54de11/ports/atmel-samd/common-hal/busio/I2C.c#L122-L132

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #6669.

Incorrect boolean operator introduced when consolidating error messages and checks.

Tested on a Metro M4.

### CODE REVIEW

File: ports/atmel-samd/common-hal/busio/I2C.c [hunk 1]
```diff
@@ -123,7 +123,7 @@ void common_hal_busio_i2c_construct(busio_i2c_obj_t *self,
     // The maximum frequency divisor gives a clock rate of around 48MHz/2/255
     // but set_baudrate does not diagnose this problem. (This is not the
     // exact cutoff, but no frequency well under 100kHz is available)
-    if (frequency < 95000 &&
+    if (frequency < 95000 ||
```
Comment (ladyada) [inline ports/atmel-samd/common-hal/busio/I2C.c:126]: plz `if ((frequency < 95000) || (i2c_m_sync_set_baudrate(&self->i2c_desc, 0, frequency / 1000) != ERR_NONE)`

Comment (dhalbert) [reply ports/atmel-samd/common-hal/busio/I2C.c:126]: done

**Review by ladyada — APPROVED** [review]
