### PR TITLE
rp2pio: Transfer up to 32 bytes before checking background tasks

### LINKED ISSUE #4135: rp2040 -- neopixels not working properly
I am having trouble controlling neopixels on  a Pico when using the neopixel.py libray
Here is an example

````
Adafruit CircuitPython 6.2.0-beta.1-80-gadaf43d6d on 2021-02-04; Raspberry Pi Pico with rp2040
>>> 
>>> import board,neopixel
>>> pix = neopixel.NeoPixel(board.GP27,8)
>>> pix[0]= 0xff   --- OK  -- pixle 0 is red
>>> pix[0]= 0xff00  --- neopixel 0 turns off
>>> pix[1]= 0xff00  --- neopixel 0 is blue ???
>>> 
```

I have tried it with a few different neopixel strings -- same behavior

### PR DESCRIPTION
**Pull request by jepler**
@Jerryneedell noticed that this problem affected strips short enough to not use the DMA peripheral, thanks for the hot tip!

Instead of checking for background tasks after every byte transfer, try up to 32 transfers before attending to background tasks.

This fixes the problem I was seeing on my 5-pixel circuit.

Closes #4135.

I wrote this before seeing the simpler #4149.  I think this _MAY_ be a bit better than #4149, and here's why:  Occasionally, background tasks and interrupts can immediately create new background tasks.  This PR would ensure that up to 32 bytes were made available to the PIO peripheral before attending to them, while that one doesn't.

### CODE REVIEW

**Comment by jerryneedell** [comment]
Thanks -- I'll try this later today -- Credit goes to @gamblor21 for finding the DMA link to this issue.

**Comment by ladyada** [comment]
good teamwork - amazing!

**Comment by gamblor21** [comment]
I agree yours is a better implementation. I did not want to remove the background tasks all together as I wasn't sure of any potential side effects.

**Comment by jerryneedell** [comment]
Sorry to report this still not working for me.

using a 7 pixel jewel:


```
dafruit CircuitPython 6.2.0-beta.1-128-g5423e4966 on 2021-02-08; Raspberry Pi Pico with rp2040

>>> from board import *
>>> import neopixel
>>> import time
>>>  
>>> pixpin = GP27
>>> numpix = 7
>>>  
>>> strip = neopixel.NeoPixel(pixpin, numpix, brightness=0.3)
>>> strip.fill(0)
>>> strip.fill(0xff)
>>> strip.fill(0xff00)
>>> strip.fill(0xff0000)
>>> 
```  after the last write, pixel 0 is green -- all others are red....

**Comment by jerryneedell** [comment]
also ```Adafruit CircuitPython 6.2.0-beta.1-128-g5423e4966 on 2021-02-08; Raspberry Pi Pico with rp2040
>>> from digitalio import *
>>> from board import *
>>> import neopixel
>>> import time
>>>  
>>> pixpin = GP27
>>> numpix = 7
>>>  
>>> strip = neopixel.NeoPixel(pixpin, numpix, brightness=0.3)
>>> strip.fill(0)
>>> strip[0]=0xff
>>> strip[0]=0xff00
>>> strip[1]=0xff00
>>> strip[1]=0xff
>>> strip[0]=0xff
>>> strip[0]=0xff00
>>> 

pixel 0 is not responding properly.

**Comment by jerryneedell** [comment]
hmm -- I had an "Airlift" connected to the Pi - it was not being used, but now that I have disconnected it, I am so far not able to reproduce the issues -- more testing to do....

**Comment by jerryneedell** [comment]
I have been unable to reproduce the issue with the Airlift disconnected....

**Comment by jerryneedell** [comment]
To be fair, I had more that just the Airlift connected.
I had the following connected:
ARILIFT -- lots of pins near the pin used for the neopixel
10Kpullups on SDA.SCL (GP0,GP1)  - were for a previous test
pushbutton from RUN to GND  -- to facilitate entering bootloader.

I have not determined which was the culprit...yet   ... I just assumed it was the Airlift -- perhaps hastily.

With just the bare Pico -- my "jewel" is behaving very normally with this PR.

**Comment by jepler** [comment]
@jerryneedell let's talk about this in the discord meeting today

**Comment by jerryneedell** [comment]
Tested with #4160 -- both are working for me.

**Review by dhalbert — APPROVED** [review]
Tested by @jerryneedell and @gamblor21.

File: ports/raspberrypi/common-hal/rp2pio/StateMachine.c [hunk 1]
```diff
@@ -546,15 +546,23 @@ static bool _transfer(rp2pio_statemachine_obj_t *self,
...
+                    --tx_remaining;
+                    did_transfer = true;
+                }
+                if (rx_remaining && !pio_sm_is_rx_fifo_empty(self->pio, self->state_machine)) {
+                    *data_in = (uint8_t) *rx_source;
+                    data_in++;
+                    --rx_remaining;
+                    did_transfer = true;
+                }
+                if (!did_transfer) {
```
Comment (tannewt) [inline ports/raspberrypi/common-hal/rp2pio/StateMachine.c:563]: I think it'd be clearer if you replaced the original if statements with while loops. That way you'd load up the 4 or 8 entry FIFO and then move on. 32 seems arbitrary and I'm skeptical you'd ever hit that many due to the FIFO size.

**Review by tannewt — COMMENTED** [review]
One suggestion to simplify things. (I realize I'm a bit late. Thanks for fixing this!)

File: ports/raspberrypi/common-hal/rp2pio/StateMachine.c (hunk 1 above)
Comment (jepler) [reply ports/raspberrypi/common-hal/rp2pio/StateMachine.c:563]: I chose 32 because it was the DMA threshold.  I didn't check the FIFO size at all!  I'll open an issue suggesting the clean-up, but try to get to it next time I'm working in this code.
