### PR TITLE
Fix signedness bug causing PIO hang-up.

### LINKED ISSUE #10157: rotaryio freezes when creating 6 IncrementalEncoder on RP2040
### CircuitPython version and board name

```python
Adafruit CircuitPython 9.2.5 on 2025-03-19; Raspberry Pi Pico with rp2040
```

### Code/REPL

```python
import board
import rotaryio

encoder_pins = [
    (board.GP0, board.GP1),
    (board.GP2, board.GP3),
    (board.GP4, board.GP5),
    (board.GP6, board.GP7),
    (board.GP8, board.GP9),
    (board.GP10, board.GP11),
    (board.GP12, board.GP13),
    (board.GP14, board.GP15),
    (board.GP16, board.GP17),
    (board.GP18, board.GP19),
]

encoders = []

print("setup encoders")
# Initialize encoders
for pin_a, pin_b in encoder_pins:
    print(f"Encoder at {pin_a}, {pin_b}")
    encoder = rotaryio.IncrementalEncoder(pin_a, pin_b)
    encoders.append(encoder)
```

### Behavior

Prints out:
```
code.py output:
setup encoders
Encoder at board.GP0, board.GP1
Encoder at board.GP2, board.GP3
Encoder at board.GP4, board.GP5
Encoder at board.GP6, board.GP7
Encoder at board.GP8, board.GP9
Encoder at board.GP10, board.GP11
```
And freezes there, ctrl-C doesn't stop the code.

### Description

I would expect an exception being raised when using too many encoders.
Or is it supposed to support like 8 encoders ?
Seems like a followup to #10024 

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by eightycc**
Fixed signed-ness bug in `State_Machine.c:use_existing_program()` where `state_machine` was unsigned but tested for less than 0. This was causing wrap-around indexing and other incorrect behavior resulting in a hang-up.

Fixed processor-dependent includes that would cause RP2350 builds not to use third PIO.

Fixed hard-crash when de-initing PIO state machine that did not completely init due to exhaustion of PIO state machines.

Fixes #10157.

### CODE REVIEW

File: ports/raspberrypi/common-hal/rp2pio/StateMachine.c [hunk 1]
```diff
@@ -336,6 +342,8 @@ bool rp2pio_statemachine_construct(rp2pio_statemachine_obj_t *self,
         }
     }
 
+    // Sanity check that state_machine number is valid.
+    assert(state_machine >= 0);
```
Comment (jepler) [inline ports/raspberrypi/common-hal/rp2pio/StateMachine.c:346]: assert is fine here since this condition should be logically impossible. Failure to allocate the state machine should have been handled with a user-visible exception above.

If it's something that MIGHT happen and it doesn't just hose the whole microcontroller until reset, it's more usual to throw an exception instead.

**Review by jepler — APPROVED** [review]
thanks! Looks good.

File: ports/raspberrypi/common-hal/rp2pio/StateMachine.c [hunk 2]
```diff
@@ -14,11 +14,17 @@
 #include "shared-bindings/microcontroller/Pin.h"
 #include "shared-bindings/memorymap/AddressRange.h"
 
+#if defined(PICO_RP2040)
 #include "src/rp2040/hardware_regs/include/hardware/platform_defs.h"
+#include "src/rp2040/hardware_structs/include/hardware/structs/iobank0.h"
+#elif defined(PICO_RP2350)
+#include "src/rp2350/hardware_regs/include/hardware/platform_defs.h"
+#include "src/rp2350/hardware_structs/include/hardware/structs/iobank0.h"
```
[the remark this answers is not in the document]
Comment (eightycc) [reply ports/raspberrypi/common-hal/rp2pio/StateMachine.c:22]: Added note to #10181. Great suggestion!

File: ports/raspberrypi/common-hal/rp2pio/StateMachine.c (hunk 1 above)
Comment (eightycc) [reply ports/raspberrypi/common-hal/rp2pio/StateMachine.c:346]: Only affects DEBUG=1 builds, so no harm. I'll remove it the next time I touch this module.
