### PR TITLE
Add caveat for usb_cdc.Serial.connected; fix another doc bug

### LINKED ISSUE #4345: usb_cdc.serials[1].connected always return False for Raspberry Pi Pico
**Firmware**

```python
Adafruit CircuitPython 6.2.0-beta.3 on 2021-03-04; Raspberry Pi Pico with rp2040
```

**Code/REPL**

```python
import usb_cdc
usb_cdc.serials[1].connected
```

**Behavior**

Running the following code ALWAYS returns `False`, even when reading data to/from the Raspberry Pi Pico, on that USB CDC channel.

```python
>>> import usb_cdc
>>> usb_cdc.serials[1].connected
False
```

**Additional Info**

Despite returning `False`, the link is working properly.

I can send and receive data, without any issues.

<hr>

According to this: https://circuitpython.readthedocs.io/en/latest/shared-bindings/usb_cdc/index.html
> True if this Serial is connected to a host. (read-only)

Since it is connected to a host, should return `True`.

And no, the Raspberry Pi Pico is the only device connected to serial, and both ports belong to it:
image

### LINKED ISSUE #4352: Small "Doc Bug" in "circuitpython.readthedocs.io/en/latest/shared-bindings/countio/index.html"
The small example in the section above contains an small error:
```python
import countio
import time
from board import *

# error "board not defined" here -> pin_counter = countio.Counter(board.D1)
pin_counter = countio.Counter(D1) # this is the fix
#reset the count after 100 counts
while True:
    if pin_counter.count == 100:
        pin_counter.reset()
    print(pin_counter.count)
```
Thomas

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #4345.
Fixes #4352.

These are documentation changes only.

### CODE REVIEW

**Comment by ismael-miguel** [comment]
Loosely related to issue #4345:

The usb_cdc documentation (https://circuitpython.readthedocs.io/en/latest/shared-bindings/usb_cdc/index.html) is missing the following methods :
- readline() - returns `bytearray`, takes 0 or 1 argument, seems to be a [`_typing.WriteableBuffer`](https://circuitpython.readthedocs.io/en/latest/shared-bindings/_typing/index.html#typing.WriteableBuffer)) or some sort of stream
- readlines() - returns array of `bytearray`

Aditionally, it is missing any information about how to change the newline character, if possible at all.

File: shared-bindings/usb_cdc/Serial.c [hunk 1]
```diff
@@ -64,6 +63,28 @@
...
 //|
+//|     def readline(self, size=-1) -> Optional[bytes]:
+//|         r"""Read a line, ending in a newline character ("\\n"), or
+//|         return everything readable if no newline is found and ``timeout`` is 0.
+//|         Return ``None`` in case of error.
+//|
+//|         This is a binary stream: the newline character cannot be changed.
+//|
+//|         :param int size: maximum number of characters to read. ``-1`` means as many as possible.
+//|         :return: the line read
```
Comment (ismael-miguel) [inline shared-bindings/usb_cdc/Serial.c:74]: The read line will include the `\r` character at the end:
image

Comment (jepler) [reply shared-bindings/usb_cdc/Serial.c:74]: Yes, the newline character is always `b'\n'` and `b'\n'` and it is preserved (if present) in the return value of readline.  It might be missing if the `readline()` call terminates due to timeout instead, so it is also useful. From what I can see, this matches pyserial.

**Review by jepler — DISMISSED** [review]

**Comment by jepler** [comment]
@dhalbert I think this is good to go but I'm leaving un-merged in case you want to make any change related to @ismael-miguel's review comment (and the build's not finished anyway)

File: shared-bindings/usb_cdc/Serial.c (hunk 1 above)
Comment (ismael-miguel) [reply shared-bindings/usb_cdc/Serial.c:74]: I know, just pointing this out as it isn't described in the file.

Comment (dhalbert) [reply shared-bindings/usb_cdc/Serial.c:74]: I will add one more sentence making this super-clear.

File: shared-bindings/usb_cdc/Serial.c [hunk 2]
```diff
@@ -68,7 +68,8 @@
 //|         return everything readable if no newline is found and ``timeout`` is 0.
 //|         Return ``None`` in case of error.
 //|
-//|         This is a binary stream: the newline character cannot be changed.
+//|         This is a binary stream: the newline character "\\n" cannot be changed.
+//|         If the host computer transmits "\\r" it will be included as part of the line.
```
Comment (ismael-miguel) [inline shared-bindings/usb_cdc/Serial.c:72]: The character in the line 72 is supposed `"\n"`, instead of the `"\r"`.

Comment (dhalbert) [reply shared-bindings/usb_cdc/Serial.c:72]: Both are true. I meant that `\r` is not considered to be a newline, it's just another character.

**Comment by dhalbert** [comment]
Anybody can review and merge.

**Review by jepler — APPROVED** [review]
Thank you.
