### PR TITLE
only add circuitpython_splash to display if it's not in another group

### LINKED ISSUE #7824: Group already in use when instantiating 2 displays
### CircuitPython version

```python
Adafruit CircuitPython 8.0.5 on 2023-03-31; Adafruit Monster M4SK with samd51j19
```

### Code/REPL

```python
import board
import busio
import digitalio
import displayio
from adafruit_st7789 import ST7789

displayio.release_displays()

# Left screen spi bus
left_spi = busio.SPI(board.LEFT_TFT_SCK, MOSI=board.LEFT_TFT_MOSI)
left_tft_cs = board.LEFT_TFT_CS
left_tft_dc = board.LEFT_TFT_DC
left_display_bus = displayio.FourWire(
    left_spi, command=left_tft_dc, chip_select=left_tft_cs
)
left_display = ST7789(left_display_bus, width=240, height=240, rowstart=80)

# right display spi bus
right_spi = busio.SPI(board.RIGHT_TFT_SCK, MOSI=board.RIGHT_TFT_MOSI)
right_tft_cs = board.RIGHT_TFT_CS
right_tft_dc = board.RIGHT_TFT_DC

right_display_bus = displayio.FourWire(
    right_spi,
    command=right_tft_dc,
    chip_select=right_tft_cs,
    reset=board.RIGHT_TFT_RST,
)

self.right_display = ST7789(
    right_display_bus, width=240, height=240, rowstart=80
)
```

### Behavior

```py
Adafruit CircuitPython 8.0.5 on 2023-03-31; Adafruit Monster M4SK with samd51j19
>>> import bugtest
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "bugtest.py", line 30, in <module>
  File "adafruit_st7789.py", line 64, in __init__
ValueError: Group already used
>>> 
```

### Description

This is because displayio.Display() attempts to assign the terminal group as the root group of every new display, regardless of whether it was already set to another display. And `common_hal_displayio_display_set_root_group` raises an exception.

The init code could call `displayio_display_core_set_root_group` directly and ignore the return value instead ?

https://github.com/adafruit/circuitpython/blob/e8711ee836eba9248cf4a73cd3e06ecf91d3e15c/shared-module/displayio/Display.c#L137-L139

https://github.com/adafruit/circuitpython/blob/e8711ee836eba9248cf4a73cd3e06ecf91d3e15c/shared-module/displayio/Display.c#L407-L413

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by FoamyGuy**
resolves #7824 

Tested successfully on Monster M4sk

Not sure if we need to guard more cautiously against `circuitpython_splash` being null or not having `in_group`. This code assumes it will exist and have that property to check. It does seem safe after testing on Monster M4sk but I don't know if there are other scenarios that could be problematic.

### CODE REVIEW

File: shared-module/displayio/Display.c [hunk 1]
```diff
@@ -136,7 +136,9 @@ void common_hal_displayio_display_construct(displayio_display_obj_t *self,
 
     // Set the group after initialization otherwise we may send pixels while we delay in
     // initialization.
-    common_hal_displayio_display_set_root_group(self, &circuitpython_splash);
+    if (!circuitpython_splash.in_group) {
```
Comment (gamblor21) [inline shared-module/displayio/Display.c:139]: This code looks fine, but I noticed a few lines later it checks if `root_group` is NULL and if so assigns it to `circuitpython_splash` with no checks and not using the function. Not sure how that may affect anything. But your check on its own looks good.

Comment (Neradoc) [reply shared-module/displayio/Display.c:139]: Are you talking about when calling `display.show(None)` ? It uses `common_hal_displayio_display_show` which does a few checks, including if the group is already in a group, and returns False when those checks fail. That return is checked and an exception is raised in the shared-bindings part:
https://github.com/adafruit/circuitpython/blob/4e7bbf70a67fe15a135ad859fa04c13bcef4fde3/shared-bindings/displayio/Display.c#L261-L264
Maybe it could use `common_hal_displayio_display_set_root_group` instead. (`show()` is deprecated anyway).

**Comment by FoamyGuy** [comment]
The latest commit adds the same check as the original commit but to a different section of code inside reset_display() which had caused trouble raised by #7472

**Review by tannewt — APPROVED** [review]
Looks good to me! Thank you!
