### PR TITLE
Reset timers separate from pwmio

### LINKED ISSUE #5057: “All timers in use” from AudioOut() after 4 soft reloads on PewPew M4
### CircuitPython version

```python
Adafruit CircuitPython 7.0.0-alpha.5-42-g0a3c75c43 on 2021-07-25; PewPew M4 with samd51g19
```

### Code/REPL

```python
import audioio, board; a = audioio.AudioOut(board.SPEAKER)
```

### Behavior

```
Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.5-42-g0a3c75c43 on 2021-07-25; PewPew M4 with samd51g19
>>> import audioio, board; a = audioio.AudioOut(board.SPEAKER)
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.5-42-g0a3c75c43 on 2021-07-25; PewPew M4 with samd51g19
>>> import audioio, board; a = audioio.AudioOut(board.SPEAKER)
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.5-42-g0a3c75c43 on 2021-07-25; PewPew M4 with samd51g19
>>> import audioio, board; a = audioio.AudioOut(board.SPEAKER)
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.5-42-g0a3c75c43 on 2021-07-25; PewPew M4 with samd51g19
>>> import audioio, board; a = audioio.AudioOut(board.SPEAKER)
>>> 
soft reboot

Auto-reload is on. Simply save files over USB to run them or enter REPL to disable.

Code done running.

Press any key to enter the REPL. Use CTRL-D to reload.

Adafruit CircuitPython 7.0.0-alpha.5-42-g0a3c75c43 on 2021-07-25; PewPew M4 with samd51g19
>>> import audioio, board; a = audioio.AudioOut(board.SPEAKER)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
RuntimeError: All timers in use
>>>
```

### Description

Creating an `audioio.AudioOut` instance, then soft-reloading using `^D` works four times, the fifth time it raises a `RuntimeError: All timers in use`. Apparently something is not properly being reset in the soft reload.

This appears to be specific to the PewPew M4, maybe related to its display initialization. I cannot reproduce it on an ItsyBitsy M4 Express using the same firmware version. (It can however be reproduced by installing the PewPew M4 firmware on the ItsyBitsy, for those who don’t have a PewPew M4.)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by tannewt**
This prevents timer leakage on builds without pwmio.

Fixes #5057

### CODE REVIEW

File: ports/atmel-samd/common-hal/pwmio/PWMOut.c [hunk 1]
```diff
@@ -97,32 +79,14 @@ void pwmout_reset(void) {
...
-        if (tccs[i]->CTRLA.bit.ENABLE == 1) {
-            tccs[i]->CTRLA.bit.ENABLE = 0;
-            while (tccs[i]->SYNCBUSY.bit.ENABLE == 1) {
-            }
-        }
         uint8_t mask = 0xff;
         for (uint8_t j = 0; j < tcc_cc_num[i]; j++) {
             mask <<= 1;
         }
         tcc_channels[i] = mask;
```
Comment (jepler) [inline ports/atmel-samd/common-hal/pwmio/PWMOut.c:89]: can the loop be eliminated, giving `tcc_channels[i].mask = 0xff << tcc_cc_num[i];` ?  (This code does have to remain here, as tcc_channels[] is only used in PWMOut)

(I don't know what the significance of these values is)

File: ports/atmel-samd/Makefile [hunk 2]
```diff
@@ -322,6 +322,14 @@ SRC_C += \
...
 	timer_handler.c \
 
+ifeq ($(CIRCUITPY_PWMIO),1)
+SRC_C += shared_timers.c
+endif
+
+ifeq ($(CIRCUITPY_AUDIOIO),1)
+SRC_C += shared_timers.c
+endif
+
```
Comment (dhalbert) [inline ports/atmel-samd/Makefile:332]: I think this would cause duplicate `.o` files when linking. It may link but I think it may grow the resulting link. We don't `$(sort` the `OBJ` value to prevent this.

I tried a very simple example:
foo.c:
```c
int int1;
int int2;
```
main.c:
```c
extern int int1, int2;

int main() {
    return int1 + int2;
}
```
Linking `foo.o` once vs twice causes different-size executables:
```sh
$ gcc main.c foo.c
$ gcc -c main.c foo.c
$ gcc -o 1.out main.o foo.o
$ gcc -o 2.out main.o foo.o foo.o
$ ls -l ?.out
-rwxrwxr-x 1 halbert halbert 16552 Aug 11 13:36 1.out
-rwxrwxr-x 1 halbert halbert 16576 Aug 11 13:36 2.out
```
It's possible to do a boolean OR with gnu make, but it's not obvious:
https://stackoverflow.com/questions/7656425/makefile-ifeq-logical-or

We could `$(sort` to remove the duplicates. We already do that with the dirs:
https://github.com/adafruit/circuitpython/blob/1e53cf40ad5dba1c28f7f179c9f30b4f60ec3da2/py/mkrules.mk#L107-L112

**Review by cwalther — APPROVED** [review]
Looks good to me and the CI build appears to work fine on the PewPew M4, fixing the problem.

**Comment by tannewt** [comment]
I'm waiting for #5100 to be merged since it should free up some space.

**Review by microDev1 — APPROVED** [review]
> `blm_badge` `fr` build is overflowing.

This is now fixed.
