### PR TITLE
fix OneWire timing and DigitalInOut.switch_to_input()

### LINKED ISSUE #964: OneWire not working in CP 3.0.0 rc0
REF: https://forums.adafruit.com/viewtopic.php?f=60&t=137405

D5 is a special pin on the Itsy, but even using D7 for testing indicates something is not working: 
### CP 2.3.1
```python
Adafruit CircuitPython 2.3.1 on 2018-05-07; Adafruit Itsy Bitsy M0 Express with samd21g18
>>> import board, busio
>>> ow = busio.OneWire(board.D7)
>>> ow.write_bit(1)
```
cp2 3 1_write_bit
### CP 3.0.0 rc0
```python
Adafruit CircuitPython 3.0.0-rc.0 on 2018-06-18; Adafruit ItsyBitsy M0 Express with samd21g18
>>> import board, busio
>>> ow = busio.OneWire(board.D7)
>>> ow.write_bit(1)
```
cp3 0 0rc0_write_bit

### PR DESCRIPTION
**Pull request by dhalbert**
OneWire didn't work at all, just sending one long pulse. `common_hal_digitalio_digitalinout_switch_to_input()` was buggy, actually failing to change the port direction. Fixed, and cleaned up `DigitalInOut.c` a bit, using `hri_` calls to save a bit of time in certain cases, and avoiding some redundant operations.

After that fix, OneWire was sort of working, but acting erratically, sometimes getting a CRC error. This problem was not present in 2.x. OneWire does bit-banging with precise time intervals using non-interruptable time-delay calls for small numbers of microseconds. It turns off interrupts while making these calls. But it was using `common_hal_mcu_delay_us()`, which calls `tick_delay()`, which depends on an interrupt to handle `SysTick` reaching zero. So the time-delay calls were inaccurate in cases when `SysTick` reached zero would have interrupted, but could not. This was not a problem in 2.x because 2.x did not use `SysTick` for general time-keeping, but only for delay operations.

Replaced the `common_hal_mcu_delay_us()` calls in `OneWire.c` with calls to a new routine just loops to use up time. Loop was calibrated on both SAMD21 and SAMD51 with the standard 48MHz and 120MHz clock frequencies.

Tested on Metro M0 and M4. Fixes #964.

### CODE REVIEW

File: ports/atmel-samd/mphalport.c [hunk 1]
```diff
@@ -75,6 +103,24 @@ void mp_hal_delay_us(mp_uint_t delay) {
...
+// Testing done at 48 MHz on SAMD21 and 120 MHz on SAMD51, multiplication and division cancel out.
+// But get the frequency just in case.
+#ifdef SAMD21
+#define DELAY_LOOP_ITERATIONS_PER_US ( (10U*48000000U) / common_hal_mcu_processor_get_frequency())
+#endif
+#ifdef SAMD51
+#define DELAY_LOOP_ITERATIONS_PER_US ( (30U*120000000U) / common_hal_mcu_processor_get_frequency())
+#endif
+
+void mp_hal_delay_us_loop(uint32_t us) {
```
Comment (tannewt) [inline ports/atmel-samd/mphalport.c]: No need to add another API. Just make `mp_hal_delay_us` this implementation. It shouldn't be used for >1ms timing.

**Comment by dhalbert** [comment]
updated and travis is happy
