### PR TITLE
Sd card usb presentation fixes

### LINKED ISSUE #10632: SAMD51: mounting SD card causes crash
Between 10.0.0-alpha.4 and alpha.5, this `code.py` started crashing on SAMD51, specifically PyPortal:

```
import board
import sdcardio
import storage
import time

spi = board.SPI()
cs = board.SD_CS

print("mounting sd card...")
sdcard = sdcardio.SDCard(spi, cs)
vfs = storage.VfsFat(sdcard)
storage.mount(vfs, "/sd")
print("sd card mounted")

while True:
    print("sleep 1")
    time.sleep(1)
```
It prints `sleep 1` once and then hangs.

I'm testing on other ports as well. On an RP2040 Metro it does not crash, but often I get "no SD card", and it requires a hard power-cycle. Also on RP2040, a drive for the SD card appears on Linux, but is not mounted.

#10351 is a possibly relevant PR that was included in alpha.5. I am thinking this all has to do with auto-USB-presentation of secondary mounts.

### PR DESCRIPTION
**Pull request by dhalbert**
- Fixes #10632.
- Does _not_ deal with #10510, which touches some of the same code, but I'll put that in a separate PR after some further consultation.
---
#### SD card USB presentation
- Add new `.h`-only compile option `CIRCUITPY_SDCARD_USB`, which will enable/disable presenting SD card as a USB MSC LUN.
- Enable on all ports except `atmel-samd` due to some bug that causes USB disconnection. I tested most of the other ports, and they don't have this problem. I'll open a separate issue about this for fixing post 10.0.0.
#### Prevent unneeded auto-reload
- Do not trigger an auto-reload if the host is doing a USB write that is not to the filesystem, but instead to the volume metadata (probably this is only the dirty bit being set/cleared). This prevents random long-interval auto-reloads (like 70 seconds) on Linux. macOS and Windows didn't have this problem. I check for this by seeing whether the LBA being written is below the FAT filesystem.
#### Technical debt found in passing
- Use `gc_ptr_on_heap()` instead of `gc_nbytes() > 0` when checking if an object on the heap. Will be slightly faster.
- Reformatted some code with preprocessor guides around line 300 in `supervisor/shared/usb/usb_msc_flash.c` so the editor does not mess up the indentation.

### CODE REVIEW

File: ports/espressif/mpconfigport.h [hunk 1]
```diff
@@ -17,6 +17,11 @@
 
 #define CIRCUITPY_DIGITALIO_HAVE_INPUT_ONLY (1)
 
+// // Present SD card as USB MSC device by default
+// #ifndef CIRCUITPY_SDCARD_USB
+// #define CIRCUITPY_SDCARD_USB (1)
+// #endif
```
Comment (tannewt) [inline ports/espressif/mpconfigport.h]: Want to uncomment this or delete it?

File: supervisor/shared/usb/usb_msc_flash.c [hunk 2]
```diff
@@ -45,6 +45,11 @@ static bool ejected[LUN_COUNT] = { [0 ... (LUN_COUNT - 1)] = true};
 static bool eject_once[LUN_COUNT] = { [0 ... (LUN_COUNT - 1)] = false};
 static bool locked[LUN_COUNT] = { [0 ... (LUN_COUNT - 1)] = false};
 
+// Set to true if a write was in a file data or metadata area,
+// as opposed to in the filesystem metadata area (e.g., dirty bit).
```
Comment (tannewt) [inline supervisor/shared/usb/usb_msc_flash.c:49]: Will file or directory deletions still trigger a reload?

**Review by tannewt — CHANGES_REQUESTED** [review]
Minor things. Want to document this behavior somewhere? Maybe the workflow markdown?

File: ports/espressif/mpconfigport.h (hunk 1 above)
Comment (dhalbert) [reply ports/espressif/mpconfigport.h]: oops - will delete

File: supervisor/shared/usb/usb_msc_flash.c (hunk 2 above)
Comment (dhalbert) [reply supervisor/shared/usb/usb_msc_flash.c:49]: Yes, the FAT, where directory data lives, is at `vfs->fatfs.fatbase` and above. The dirty bit and other volume metadata is below `fatbase`.

Volume structure is documented at https://download.microsoft.com/download/0/8/4/084C452B-B772-4FE5-89BB-A0CBF082286A/fatgen103.doc

**Comment by dhalbert** [comment]
> Want to document this behavior somewhere? Maybe the workflow markdown?

I added a paragraph to the `#### SD card drive` section in `workflows.md`.

File: docs/workflows.md [hunk 3]
```diff
@@ -44,6 +44,12 @@ A few boards have SD card automounting. (This is based on the ``DEFAULT_SD`` set
 ``mpconfigboard.h``.) The card is writable from CircuitPython by default and read-only to the host.
 `storage.remount()` can be used to remount the drive to the host as read-write.
 
+On most other boards, except for ``atmel-samd`` boards, an SD card mounted in user code
+at ``/sd`` will become visible after a few seconds on the attached host computer, as an
+additional drive besides CIRCUITPY and (if present) CPSAVES. It will present with the volume
+label on the SD card. Depending on the host operating system settings, the drive may or may not be
+auto-mounted on the host.
```
Comment (tannewt) [inline docs/workflows.md]:
```suggestion
auto-mounted on the host. Writes to user code mounted drives will not trigger a reload.
```

Comment (dhalbert) [reply docs/workflows.md]: I added this sentence, in a slightly different form.

**Review by tannewt — APPROVED** [review]
Looks good! Thank you!
