### PR TITLE
mimxrt1011: UART: Add additional error checking

### LINKED ISSUE #4502: Hardfault when picking wrong UART pin on iMX RT1011
```
import board
import busio

uart = busio.UART(None, board.TX, baudrate=9600)

while True:
   pass
```
i should be passing board.RX in there, was testing if the wrong pin is passed...it hardfaults when instead we should get an exception that the pin cannot be used as a uart RX!

### PR DESCRIPTION
**Pull request by jepler**
.. and make the 'invalid pin' messages standard.

Closes #4502

### CODE REVIEW

**Comment by jepler** [comment]
Running uart_test_script on the rt1010-evk:
```
>>> import uart_test_script
RX pin: board.D6 	 TX pin: board.D7
RX pin: board.D6 	 TX pin: board.AUDIO_BCLK
RX pin: board.A0 	 TX pin: board.AUDIO_MCLK
RX pin: board.AUDIO_SYNC 	 TX pin: board.AUDIO_MCLK
RX pin: board.USER_LED 	 TX pin: board.AUDIO_MCLK
RX pin: board.D0 	 TX pin: board.D1
```

**Review by ladyada — APPROVED** [review]

File: ports/mimxrt10xx/common-hal/busio/UART.c [hunk 1]
```diff
@@ -202,16 +209,19 @@ void common_hal_busio_uart_construct(busio_uart_obj_t *self,
...
         if (self->cts == NULL) {
-            mp_raise_ValueError(translate("Selected CTS pin not valid"));
+            mp_raise_ValueError_varg(translate("Invalid %q pin"), MP_QSTR_CTS);
         }
     }
 
     if (self->rx) {
         self->uart = mcu_uart_banks[self->rx->bank_idx - 1];
     } else {
+        assert(self->rx);
```
Comment (d-c-d) [inline ports/mimxrt10xx/common-hal/busio/UART.c:219]: was the assert(self->rx) a known failure, since we just checked self-rx above, so we know it's false
compare that to the self-tx and self-uart usages below
