### PR TITLE
Remove OSError(0) and old network modules

### LINKED ISSUE #1880: Better exceptions for 'socket', 'network', 'wiznet' libraries
At the moment, the exceptions raised by 'socket', 'network' and 'wiznet' libraries are mostly just in the form `mp_raise_OSError(_errno)` which leads to irritatingly nonspecific exceptions like `OSError: [Errno 4]`.

We should improve these to have proper error messages.

See also #703 (initial implementation from micropython) #1800 (bugfixes for 4.0.0)

### LINKED ISSUE #2273: wiznet.WIZNET5K constructor needs better arg validation
A user did
```
eth = wiznet.WIZNET5K(board.SPI, board.D10, dhcp=True)
```
but actually meant to do:
```
eth = wiznet.WIZNET5K(board.SPI(), board.D10, dhcp=True)
```

The `board.SPI` as an arg caused a fatal crash, which makes me think WIZNET5K is not validating its args completely.

### LINKED ISSUE #2274: Wiznet Ethernet Featherwing Addresses Unstable in CPy
Although the Wiznet Ethernet Featherwing, is shipped with a unique
Adafruit MAC address, there is no way to use it or enter it with
Circuit Python.  As a result, the Wiznet chip makes up a random MAC
address every time it is initialized, and gets a different DHCP
assigned IP address, hopping up and down the user's network address
space.

The initialization of the wiznet.WIZNET5K() class should provide for
a parameter of the desired MAC address, to be loaded into the Wiznet
chip before the DHCP process is started. This exists in the Arduino 
implementation, but not Circuit Python.

There are multiple network side effects and potential problems from
this kind of random MAC address hopping.

### LINKED ISSUE #3924: ESP32S2 WiFi OSErrors
I'm having problems with infrequent crashes on the MagTag that are similar to the problems I have with the Matrixportal (described [here](https://forums.adafruit.com/viewtopic.php?f=60&t=172275&p=844238#p844238)).  I've tried this with several versions of Circuit Python, and now have the board running 6.1.0-beta.3 with libraries from *-bundle-6.x-mpy-20210101.

The code is pulling data from the Purple Air and Weather Underground web sites.  It will run for a while (frequently hours) and then crash in a fetch_data() call.  I have a try/except clause around the fetch_data(), but for some reason it only catches the error occasionally.  

The code is attached the post on the forum [here](https://forums.adafruit.com/viewtopic.php?f=60&t=173673).

Here is the error:

```
> Retrieving data...Traceback (most recent call last):
>   File "code.py", line 126, in <module>
>   File "code.py", line 122, in <module>
>   File "adafruit_portalbase/network.py", line 453, in fetch_data
>   File "adafruit_portalbase/network.py", line 425, in fetch
>   File "adafruit_requests.py", line 612, in get
>   File "adafruit_requests.py", line 576, in request
>   File "adafruit_requests.py", line 436, in _get_socket
> OSError: 0
```

This is coming from this section of the code (full code attached):

           print("***inside")
           fetch_success = False

           try:
               inside = NETWORK.fetch_data(
                   url=Inside_SOURCE,
                   json_path=(PM2_Location,TEMP_Location,HUMI_Location),)
               fetch_success = True
           except RuntimeError as e:
               print("Some error occurred, retrying! -", e)
               continue

I have seen the try/except actually catch the error on some iterations.  For example, this will pop up every now and then:

```

> ***inside
> Retrieving data...Some error occurred, retrying! - Sending request failed
> Free Memory: 1,946,496
> Iteration:  13

```

I'll also file this as an issue as @siddacious suggested in the original post.

### PR DESCRIPTION
**Pull request by tannewt**
The newer modules are `socketpool` and `ssl`.

Fixes #3924, related to #2021, closes #1880, closes #2273, closes #2274

### CODE REVIEW

File: shared-bindings/socketpool/SocketPool.c [hunk 1]
```diff
@@ -123,7 +123,7 @@ STATIC mp_obj_t socketpool_socketpool_getaddrinfo(size_t n_args, const mp_obj_t
     }
 
     if (ip_str == mp_const_none) {
-        mp_raise_OSError(0);
+        mp_raise_OSError(-2);
```
Comment (jepler) [inline shared-bindings/socketpool/SocketPool.c:126]: It seems like the value passed to `mp_raise_OSError` is generally a positive errno value.  
```
py/mperrno.h:#define MP_ENOENT             (2) // No such file or directory
...
ports/unix/modffi.c:        mp_raise_OSError(MP_ENOENT);
```
but sometimes they're raised as negative values
```
extmod/vfs_lfsx.c:            mp_raise_OSError(-MP_ENOENT);
```

Does the positive/negative distinction mean something?  Should a named constant such as MP_NOENT be used here instead of the number 2?

**Review by jepler — CHANGES_REQUESTED** [review]
Thanks!  There's one thing I wanted to ask about..

File: shared-bindings/socketpool/SocketPool.c (hunk 1 above)
Comment (tannewt) [reply shared-bindings/socketpool/SocketPool.c:126]: This weird because in CPython it is this error: https://docs.python.org/3/library/socket.html#socket.gaierror The value comes from:
```
Python 3.9.6 (default, Jun 30 2021, 10:22:16) 
[GCC 11.1.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import socket
>>> socket.EAI_NONAME
-2
```

I've added a short comment about what the value is.

**Review by jepler — DISMISSED** [review]
Thanks for addressing my comment!

**Review by microDev1 — APPROVED** [review]
