### PR TITLE
Round BLE timing values; fix timeout check

### LINKED ISSUE #2930: start_advertising interval does not accept the minimum 20ms value and may not range check correctly
I was reading https://developer.apple.com/accessories/Accessory-Design-Guidelines.pdf and page 126, section 35.5 recommends "an initial 30s of 20ms intervals" for advertising if I'm understanding this correctly.

I tried it on CircuitPython and it didn't behave. I've just run it again against 5.3.0 with 20200519 libs.

```
Adafruit CircuitPython 5.3.0 on 2020-04-29; Adafruit Circuit Playground Bluefruit with nRF52840
>>>
>>> from adafruit_ble import BLERadio
>>> from adafruit_ble.advertising.adafruit import AdafruitColor
>>> ca = AdafruitColor()
>>> ca.color = 0xee0000
>>> ca
Advertisement(data=b"\x0a\xff\x22\x08\x06\x00\x00\x00\x00\xee\x00")
>>> ble = BLERadio ()
>>> ble.start_advertising(ca, interval=0.020)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ble/__init__.py", line 185, in start_advertising
_bleio.BluetoothError: Unknown soft device error: 0007
```

I had a brief discussion with @jepler on discord about this and we both assumed it was an unfortunate FP-ism. I had a glance at the code and it looks like it might unfortunately reject via an informational exception a 0.020 value because of the 30-bit fp conversion and then comparison of `< 0.020f`. The _nice exception doesn't happen_, I tried a few values to work out what's going on.

```
>>> ble.start_advertising(ca, interval=0.019)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ble/__init__.py", line 185, in start_advertising
_bleio.BluetoothError: Unknown soft device error: 0007
>>> ble.start_advertising(ca, interval=0.001)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "adafruit_ble/__init__.py", line 185, in start_advertising
ValueError: interval must be in range 0.0020-10.24
```

Are these pair (https://github.com/adafruit/circuitpython/blob/master/shared-bindings/_bleio/Adapter.c#L36-L37) supposed to read `0.020` (20ms) rather than `0.0020` (2ms)?

The code is also not doing an explicit conversion to integer so gets truncation (round towards zero) semantics and judging by a test of this code that will also punt a 30bit 0.020 value into _out of range territory_:

```
#define SEC_TO_UNITS(TIME, RESOLUTION) (((TIME) * 1000000) / (RESOLUTION))
#define UNIT_0_625_MS (625)

int main(int argc, char *argv[]) {
  float f1 = 0.020f;
  /* 0.020 into Schmidt FP tool, zero lower two digitals, take "actual" value - this is way beyond 32bit prec. */
  float f2 = 0.01999999582767486572265625f;
  float f3 = 0.02001;
  int i1, i2, i3;

  if (f2 < f1) {
    printf("TOO SMALL\n");
  };

  i1 = SEC_TO_UNITS(f1, UNIT_0_625_MS);
  i2 = SEC_TO_UNITS(f2, UNIT_0_625_MS);
  i3 = SEC_TO_UNITS(f3, UNIT_0_625_MS);

  fprintf(stdout, "%f is %d and %f2 is %d and %f2 is %d\n", f1, i1, f2, i2, f3, i3);
}
```

Output is:

```
TOO SMALL
0.020000 is 32 and 0.0200002 is 31 and 0.0200102 is 32
```

The middle one is actually the 0.020 with MicroPython's 30bit conversion applied and comes out as `31` which is below minimum.

For anyone else stumbling across this issue, the value below works as a workaround that can be left in place after any fixes:

```
>>> ble.start_advertising(ca, interval=0.02001)
```

### LINKED ISSUE #3942: Valid values for timeout of BLERadio.start_scan() seem to be ignored
Issue #3826 was fixed in 6.0.1 but the fix seems to have introduced a new bug. Any timeout value >= 0.1 seems to be ignored now (no timeout). I had the code below running for 14 min and it did not precede past "Scanning for an Adafruit Server advertisement...". I checked 6.0.0 again and the behaviour there is as expected. 
I tested this on a Feather Sense using 6.1.0 RC as well as 6.0.1.

```
import time

import adafruit_ble
from adafruit_ble_adafruit.adafruit_service import AdafruitServerAdvertisement
import supervisor

ble = adafruit_ble.BLERadio()

connection = None

print("Scanning for an Adafruit Server advertisement...")
for adv in ble.start_scan(AdafruitServerAdvertisement, timeout=1.0):
    print("about to connect")
    connection = ble.connect(adv)
    print("connected")
    break

ble.stop_scan()

supervisor.reload()
```

### PR DESCRIPTION
**Pull request by dhalbert**
Fixes #3942.
Fixes #2930.

- Fix reversed logic for `_bleio.start_scan()` no timeout check in `nrf`.
- Use error-checking float conversion in `_bleio` float argument validation.
- Round _bleio float timeout values to nearest integer quantum, instead of truncating. This solves the problem of `0.02` being not quite big enough due to float representation issues.
- Fix one float conversion in `_pixelbuf` that was not using the error-checking object-to-float conversion routine.

### CODE REVIEW

File: ports/nrf/common-hal/_bleio/Adapter.c [hunk 1]
```diff
@@ -479,15 +479,15 @@ mp_obj_t common_hal_bleio_adapter_start_scan(bleio_adapter_obj_t *self, uint8_t*
         mp_raise_ValueError(translate("non-zero timeout must be > 0.01"));
     }
 
-    if (nrf_timeout) {
+    if (nrf_timeout == 0) {
```
Comment (tannewt) [inline ports/nrf/common-hal/_bleio/Adapter.c:482]: Does 0.5f round down? Does setting unlimited still work?

**Review by tannewt — CHANGES_REQUESTED** [review]
One question.

File: ports/nrf/common-hal/_bleio/Adapter.c (hunk 1 above)
Comment (dhalbert) [reply ports/nrf/common-hal/_bleio/Adapter.c:482]: Yes, for `timeout=0.0f`, this reduces to `uint32_t nrf_timeout = 0.0f + 0.5f;`, and casting a `float` to an integer in C truncates, so `nrf_timeout` becomes `0`.

To triple-check, I actually tried `timeout=0.0`, and it scanned forever (well, I didn't wait that long).

**Review by tannewt — APPROVED** [review]
Thank you!
