### PR TITLE
Prevent freezing USB during high frequency PulseIn.

### LINKED ISSUE #516: Feather Express M0 - pulseio.PulseIN - freezes at high frequency
Test Case: 
Messure Light trough a light-to-frequency-coverter.

Test Setup: 
Feather Express M0 - Circuit Python 2.2.0 
TSL235R-LF
https://www.sparkfun.com/datasheets/Sensors/Imaging/TSL235R-LF.pdf
connected 3V to VDD, GND to GND and Output to D12

```
> #Feather Express M0 connected 3V to VDD, GND to GND and Output to D12
 import board
 from board import*
 import digitalio
 import busio
 import adafruit_ssd1306
 import time
 import analogio
 import pulseio

 i2c = busio.I2C(SCL, SDA)
 display = adafruit_ssd1306.SSD1306_I2C(128, 32, i2c)
 pulses = pulseio.PulseIn(board.D12, maxlen=20)

 while True:
     time.sleep(1)
     pulse = 500000/float(pulses[0])
     display.fill(0)
     display.text(str(pulse),0,0)
     print(pulse)
     display.show()
```

Error: 
Board do not response, crash or disconnect while the input frequency is above 25 kHz. 
The specific freqency could not be determinated. 
While covering the Converter it is sometimes possible to recover the board. Outwise a reset is nessessary.

Source: 
https://forums.adafruit.com/viewtopic.php?f=60&t=129061

### PR DESCRIPTION
**Pull request by tannewt**
We now track the last time the background task ran and bail on the
PulseIn if it starves the background work. In practice, this
happens after the numbers from pulsein are no longer accurate.

This also adjusts interrupt priorities so most are the lowest level
except for the tick and USB interrupts.

Fixes #516 and #876

### CODE REVIEW

File: ports/atmel-samd/common-hal/pulseio/PulseIn.c [hunk 1]
```diff
@@ -118,6 +125,7 @@ void common_hal_pulseio_pulsein_construct(pulseio_pulsein_obj_t* self,
     self->first_edge = true;
     self->last_us = 0;
     self->last_ms = 0;
+    self->errored_too_fast = 0;
```
Comment (dhalbert) [inline ports/atmel-samd/common-hal/pulseio/PulseIn.c]: `= false`
